/**
 * AgroTrace — Step 2 behaviour: LOGIC flows.
 * Grounded in SPEC.md Sections 3, 4, 5 (Tables 15 and 16), 7, 8 and 9.
 * A. Platform rules (flow01-flow19)
 * B. Turmeric profile status machine, one flow per Table 15 stage (flow20-flow35)
 * C. Mango profile status machine, one flow per Table 16 stage (flow36-flow47)
 * No tokens, no gas, no escrow, no payments: AgroChain is an internal permissioned ledger.
 */

const FLOWS = [
  /* ═══ A. PLATFORM RULES ═══════════════════════════════════════════════ */

  {
    id: 'flow01',
    name: 'Anchor Everything on AgroChain',
    trigger: 'Any create or record action on Lot, ResidueTest, Shipment, ShipmentEvent, Certificate, CustodyTransfer or Dispute',
    description: 'Every create or record action submits a ChainTransaction and stamps chainTxHash, chainBlockNumber and chainStatus on the record. ChainBadge shows amber at PENDING and turns green at CONFIRMED once the block is FINALISED.',
    steps: [
      'Serialise the record into a payload and compute payloadHash = sha256(payload)',
      'Build the ChainTransaction with the actor deterministic wallet as fromWallet and the matching ChainTxType',
      'Compute txHash = sha256(txData) and submit the transaction to the mempool',
      'Stamp chainTxHash and chainStatus = PENDING on the source record and render ChainBadge amber',
      'On block finalisation write chainBlockNumber, set chainStatus = CONFIRMED and flip ChainBadge to green',
      'On mining failure set chainStatus = FAILED and raise a Notification to the recording user',
    ],
  },
  {
    id: 'flow02',
    name: 'Commodity-Aware Lot ID Assignment',
    trigger: 'Lot create submitted from LotRegistrationForm',
    description: 'Derive the lot code from Lot.commodityKey and mint lotId in the form LOT-<CODE>-YYYY-NNNN. TURMERIC yields TURM and MANGO yields MANGO.',
    steps: [
      'Read Lot.commodityKey and map it to the lot code TURM or MANGO',
      'Take YYYY from Lot.harvestDate and read the next sequence number for that tenant, code and year',
      'Format lotId as LOT-<CODE>-YYYY-NNNN with the sequence zero-padded to four digits',
      'Persist lotId as unique within the tenant and set Lot.status = REGISTERED',
      'Submit a LOT_REGISTERED ChainTransaction carrying lotId and the LotRegistrationForm metadata',
    ],
  },
  {
    id: 'flow03',
    name: 'Auto-Consignment on Turmeric Lot Registration',
    trigger: 'Lot created with commodityKey = TURMERIC',
    description: 'A turmeric lot registration automatically opens a consignment so the batch lands in the first processing queue. The Shipment is created in the same transaction batch as the lot.',
    steps: [
      'Detect commodityKey = TURMERIC on the newly created Lot',
      'Create a Shipment linked to the lot with currentStatus = REGISTERED and a generated shipmentId',
      'Submit a SHIPMENT_CREATED ChainTransaction and stamp the chain proof on the Shipment',
      'Place the shipment in the LABORATORY residue-test work queue as the first processing queue',
      'Notify the LABORATORY role and the registering FARMER that the consignment is open',
    ],
  },
  {
    id: 'flow04',
    name: 'Residue and MRL Gating',
    trigger: 'ResidueTestForm submitted by a LABORATORY user',
    description: 'Each pesticideResults row is compared against the chosen mrlStandard, and the outcome sets Lot.status. A FAIL blocks export and a CONDITIONAL_PASS flags a retest.',
    steps: [
      'Read mrlStandard from the ResidueTest and load the matching limits for every pesticideResults row',
      'Compare detectedPpm against mrlLimitPpm for each compound and derive the row result',
      'On PASS set Lot.status = RESIDUE_TEST_PASSED and advance Shipment.currentStatus = RESIDUE_TESTED',
      'On FAIL set Lot.status = RESIDUE_TEST_FAILED and block every downstream export stage for the lot',
      'On CONDITIONAL_PASS set Lot.status = RESIDUE_TEST_CONDITIONAL and raise a retest flag on the lot',
      'Submit a RESIDUE_TEST_RECORDED ChainTransaction with the report documentHash',
      'Notify the EXPORTER and the FARMER of the outcome',
    ],
  },
  {
    id: 'flow05',
    name: 'Two-Party Consensus Handoff',
    trigger: 'A custody-changing ShipmentEvent is recorded by the transferring role',
    description: 'The receiving role reviews the declared quantity and records HANDOFF_ACCEPTED or HANDOFF_DISPUTED on a single HandoffSignature record that carries both signatures. The next stage is gated on acceptance.',
    steps: [
      'Create a HandoffSignature with the FROM_PARTY signature, the declared quantityKg and the actor wallet',
      'Notify the receiving role and place the handoff in its review queue',
      'Receiver compares the declared quantity and condition against what was physically received',
      'On agreement write the TO_PARTY signature with decision = HANDOFF_ACCEPTED onto the same HandoffSignature',
      'On discrepancy write decision = HANDOFF_DISPUTED, hold the shipment and alert the EXPORTER and PLATFORM_ADMIN',
      'Submit a CUSTODY_TRANSFERRED ChainTransaction and unlock the next stage only when the decision is HANDOFF_ACCEPTED',
    ],
  },
  {
    id: 'flow06',
    name: 'Status State Machine and Role Work Queues',
    trigger: 'ShipmentEvent recorded for any stage in the active commodity profile',
    description: 'Each event type maps to a resulting ShipmentStatus from the profile stage table, and queues are driven by status. A role opens to the shipments sitting at the status it acts on.',
    steps: [
      'Look up the stage row for the event type in the active commodity profile',
      'Reject the event if the shipment is not sitting at the status that stage expects',
      'Write ShipmentEvent with eventType, eventLabel, actorUserId, actorWalletAddress, actorRole and metadata',
      'Set Shipment.currentStatus to the resulting ShipmentStatus for that stage',
      'Recompute the work queue for the role that owns the new status and remove the shipment from the previous queue',
      'Submit an EVENT_RECORDED ChainTransaction and refresh the shipment detail timeline',
    ],
  },
  {
    id: 'flow07',
    name: 'Compliance Score and Cold-Chain Breach',
    trigger: 'TelemetryReading ingested from an IotDevice bound to the shipment',
    description: 'A temperature, humidity or moisture excursion sets Shipment.hasBreach and Shipment.breachType and records a BREACH_RECORDED transaction. The breach also lowers Shipment.complianceScore.',
    steps: [
      'Compare the TelemetryReading value against the target range recorded at COLD_STORAGE_ENTRY',
      'Flag the reading as a breach and classify breachType as TEMPERATURE_EXCURSION, HUMIDITY_EXCURSION or MOISTURE_EXCURSION',
      'Set Shipment.hasBreach = true and write Shipment.breachType',
      'Submit a BREACH_RECORDED ChainTransaction carrying the reading and device id',
      'Recompute Shipment.complianceScore from the ComplianceMatrix checks and the breach penalty',
      'Notify COLD_STORAGE, FREIGHT_FORWARDER, EXPORTER and BUYER through the telemetry tab and push alerts',
    ],
  },
  {
    id: 'flow08',
    name: 'Dispute Lifecycle',
    trigger: 'BUYER opens a dispute on a delivered or arrived shipment',
    description: 'A dispute runs OPEN to EXPORTER_RESPONDED to CLOSED, and closing carries a DisputeResolutionOutcome. Evidence documents attach to the dispute and are hashed and anchored.',
    steps: [
      'Create the Dispute with initiatedById, rejectionType, reasonCategory, rejectedQuantityKg, claimedValueUsd and status = OPEN',
      'Set Shipment.currentStatus = DISPUTED and submit a DISPUTE_INITIATED ChainTransaction',
      'Accept DisputeEvidence uploads from both sides, hash each file with SHA-256 and anchor the hash',
      'Record the exporter reply and move Dispute.status = EXPORTER_RESPONDED',
      'Resolve with a DisputeResolutionOutcome of EXPORTER_ACCEPTED, BUYER_ACCEPTED, PARTIAL_SETTLEMENT or REFERRED_TO_ARBITRATION',
      'Set Dispute.status = CLOSED, set Shipment.currentStatus = DISPUTE_RESOLVED and submit a DISPUTE_RESOLVED ChainTransaction',
      'Notify BUYER, EXPORTER and PLATFORM_ADMIN and write the AuditLog entry',
    ],
  },
  {
    id: 'flow09',
    name: 'Certificate Anchoring and File Verification',
    trigger: 'A document is uploaded on the shipment detail Upload certificate action',
    description: 'Phyto, COO, treatment and bill-of-lading documents are hashed with SHA-256 and anchored so the file can be verified against the ledger. Verification rehashes the stored file and compares it to the anchored hash.',
    steps: [
      'Store the file to S3 and record documentS3Key, originalFilename and fileSize on the Certificate',
      'Compute documentHash = sha256(file bytes) and write it to the Certificate',
      'Write certType, certificateNumber, issueDate, validityDate and issuingAuthority',
      'Submit a CERTIFICATE_ANCHORED ChainTransaction carrying documentHash',
      'On verify, rehash the retrieved file and compare against the anchored hash in the ChainTransaction payload',
      'Show verified or tampered on the shipment detail and on the Public Verify page',
    ],
  },
  {
    id: 'flow10',
    name: 'Record Permission Gate',
    trigger: 'Any attempt to record a ShipmentEvent',
    description: 'Only a non-admin role user may record an event on a shipment, and only while the shipment is not DELIVERED or DISPUTE_RESOLVED. Admin accounts observe but do not record.',
    steps: [
      'Reject the attempt when the caller role is PLATFORM_ADMIN or the account is flagged isSuperAdmin',
      'Reject the attempt when Shipment.currentStatus is DELIVERED or DISPUTE_RESOLVED',
      'Confirm the caller tenantId matches Shipment.tenantId and the caller commodityKey matches the lot profile',
      'Confirm the caller role owns the stage that the event type belongs to',
      'Allow the record and write an AuditLog entry with the actor, the shipment and the event type',
    ],
  },
  {
    id: 'flow11',
    name: 'Compliance Override by Platform Admin',
    trigger: 'PLATFORM_ADMIN overrides a blocked compliance check on the Compliance screen',
    description: 'A platform admin may release a shipment held by a ComplianceMatrix check, and the override is audited and anchored. The override never clears a RESIDUE_TEST_FAILED lot silently.',
    steps: [
      'Confirm the caller role is PLATFORM_ADMIN within the owning tenant',
      'Require a written justification and the identifier of the ComplianceMatrix check being overridden',
      'Record the override against the shipment and recompute Shipment.complianceScore with the override marked',
      'Submit a COMPLIANCE_OVERRIDE ChainTransaction carrying the check id, the justification hash and the admin wallet',
      'Write an AuditLog entry and notify the EXPORTER and the role whose stage was unblocked',
    ],
  },
  {
    id: 'flow12',
    name: 'Block Production and Four-of-Five Consensus',
    trigger: 'Mempool wait elapses for queued ChainTransactions',
    description: 'A round-robin producer node builds a block with a Merkle root and previousBlockHash, and the five validators vote. The block moves PENDING_CONSENSUS to FINALISED at four votes, otherwise it stays PENDING_CONSENSUS.',
    steps: [
      'Hold each submitted transaction in the mempool for a randomised 5 to 20 seconds',
      'Select the producer node round-robin across the five ChainNode validators',
      'Build the ChainBlock with the Merkle root of its transactions and previousBlockHash from the parent, using 64 zeros for genesis',
      'Compute blockHash with SHA-256 and set ChainBlock.status = PENDING_CONSENSUS',
      'Collect a ChainConsensusVote from each validator node and count the approvals',
      'At four votes or more set status = FINALISED, stamp finalisedAt and mark the member transactions CONFIRMED',
      'Below the consensusThreshold of 4 leave the block PENDING_CONSENSUS and surface it in the Chain Explorer consensus panel',
    ],
  },
  {
    id: 'flow13',
    name: 'Audit-Trail PDF Export',
    trigger: 'Audit-trail export requested from Reports for a shipment',
    description: 'An ExportJob assembles the full on-chain journey into a signed PDF and runs PENDING to PROCESSING to COMPLETE or FAILED. The PDF is signed with the platform KMS key, stored to S3 and its hash is anchored.',
    steps: [
      'Create the ExportJob with status = PENDING for the requested shipment and requesting user',
      'Move the job to PROCESSING and collect every ShipmentEvent, Certificate, CustodyTransfer, HandoffSignature and BREACH_RECORDED entry in block order',
      'Render the chronological PDF with each row carrying its txHash and blockNumber',
      'Sign the PDF with the platform KMS signing key and upload it to S3',
      'Compute the SHA-256 hash of the signed PDF and anchor it as a CERTIFICATE_ANCHORED transaction',
      'Set the job to COMPLETE with the download link, or to FAILED with the error, and notify the requester',
    ],
  },
  {
    id: 'flow14',
    name: 'Public Verify Page',
    trigger: 'A shipment QR code is scanned by anyone outside the platform',
    description: 'The QR opens a no-login public page showing the full journey, the anchored certificates and the compliance scorecard. Only published fields are exposed and no tenant-internal data is shown.',
    steps: [
      'Resolve the QR token to the shipment without requiring a session',
      'Render the on-chain event timeline with each event type, actor organisation, timestamp, txHash and block number',
      'List every Certificate with certType, certificateNumber, issuing authority and the anchored documentHash',
      'Show the compliance scorecard from Shipment.complianceScore plus hasBreach and breachType',
      'Offer per-certificate verification that rehashes the file and compares it to the ledger',
      'Hide pricing, contact details and any field not marked public in the tenant scope',
    ],
  },
  {
    id: 'flow15',
    name: 'Tenant Isolation, Role Navigation and Profile Scoping',
    trigger: 'Any authenticated request or screen load',
    description: 'Every collection is scoped to a tenant and a user only ever sees their own tenant. Navigation is a minimal allow-list per role and each user is scoped to one commodity profile.',
    steps: [
      'Resolve tenantId from the session and add it as a mandatory filter on every collection query',
      'Reject any read or write whose target record belongs to a different tenantId',
      'Build the navigation from the allow-list of screens for User.role and hide everything else',
      'Filter lots and shipments by User.commodityKey so a user sees only their commodity profile',
      'Allow PLATFORM_ADMIN to switch commodity profiles within the tenant and allow isSuperAdmin to reach Team and Users',
      'Write an AuditLog entry for every cross-scope access attempt that is denied',
    ],
  },
  {
    id: 'flow16',
    name: 'Auth Hardening',
    trigger: 'Login, token refresh or password change',
    description: 'Sessions run on JWT access plus refresh tokens with password history and login-attempt throttling. Repeated failures lock the account and raise an alert.',
    steps: [
      'Verify the credential against User.passwordHash and reject when User.status is not ACTIVE',
      'Issue a short-lived JWT access token and a refresh token bound to the session record',
      'Rotate the refresh token on every refresh and revoke the previous one',
      'On password change reject any value already present in the password history and append the new hash',
      'Throttle login attempts per account and per source, and set User.status = SUSPENDED after the configured failure count',
      'Write every login, refresh, lockout and password change to the AuditLog',
    ],
  },
  {
    id: 'flow17',
    name: 'Outbound Webhook Dispatch',
    trigger: 'Any of the ten ChainTxType transactions is submitted',
    description: 'Each enabled WebhookConfig receives an HMAC-signed POST for the transaction type it subscribes to, and each attempt is recorded as a WebhookDelivery. Failed deliveries retry with backoff.',
    steps: [
      'Match the transaction type against the subscribed types on every enabled WebhookConfig for the tenant',
      'Build the payload with txHash, txType, the record reference, blockNumber and chainStatus',
      'Sign the body with the HMAC secret of the WebhookConfig and set the signature header',
      'POST to the endpoint and create a WebhookDelivery with the response code and body',
      'Retry failed deliveries with exponential backoff up to the configured attempt limit',
      'Disable the WebhookConfig and alert the PLATFORM_ADMIN after the retry budget is exhausted',
    ],
  },
  {
    id: 'flow18',
    name: 'Stage Notifications to the Next Role',
    trigger: 'ShipmentEvent recorded and Shipment.currentStatus advanced',
    description: 'Advancing the status notifies the role that owns the next stage so the item appears in its work queue. Delivery fans out across in-app, push, SMS, WhatsApp and email by user preference.',
    steps: [
      'Resolve the next stage for the new Shipment.currentStatus from the active commodity profile',
      'Resolve the users in the owning tenant who hold the role for that stage',
      'Create a Notification per recipient with the shipment, the lot id and the action required',
      'Fan out on the channels the recipient has enabled: in-app, push, SMS, WhatsApp and email',
      'Send the field-facing channels in the recipient locale from the nine supported languages',
      'Record delivery status on each Notification and retry the failed channels once',
    ],
  },
  {
    id: 'flow19',
    name: 'Invite-Code Farmer Signup',
    trigger: 'A farmer opens the signup screen with an invite code from the exporter',
    description: 'The exporter issues an invite code that binds the new farmer to the tenant, the FARMER role and one commodity profile. The account is created in INVITED and becomes ACTIVE on first successful login.',
    steps: [
      'Validate the invite code, confirm it is unexpired and unredeemed, and read its tenantId and commodityKey',
      'Check the tenant maxParticipantAccounts limit before creating the account',
      'Create the User with role = FARMER, status = INVITED and the commodityKey carried by the code',
      'Derive the deterministic wallet address for the new user and store walletAddress',
      'Mark the invite code redeemed and set User.status = ACTIVE on first successful login',
      'Open the phone-friendly farmer portal and write an AuditLog entry for the signup',
    ],
  },

  /* ═══ B. TURMERIC PROFILE STATUS MACHINE (Table 15) ═══════════════════ */

  {
    id: 'flow20',
    name: 'Turmeric · Farmer records LOT_REGISTERED',
    trigger: 'FARMER submits LotRegistrationForm from the farmer portal',
    description: 'Registers the harvest batch as a Lot with the LotRegistrationForm fields plus the turmeric attributes for initial moisture, raw batch value and soil type. The lot is created rather than advancing a shipment status.',
    steps: [
      'Validate the required LotRegistrationForm fields including variety, harvestDate, quantityKg, apedaRegNumber and fssaiLicense',
      'Mint lotId as LOT-TURM-YYYY-NNNN from commodityKey and set Lot.status = REGISTERED',
      'Store the turmeric extras into Lot.attributes as profile-specific json',
      'Submit a LOT_REGISTERED ChainTransaction and stamp chainTxHash with chainStatus = PENDING',
      'Open the auto-consignment Shipment at currentStatus = REGISTERED',
      'Place the lot in the LABORATORY residue-test queue and notify the LABORATORY role',
    ],
  },
  {
    id: 'flow21',
    name: 'Turmeric · Laboratory records RESIDUE_TEST_RECORDED',
    trigger: 'LABORATORY submits ResidueTestForm for a registered turmeric lot',
    description: 'Records the ResidueTest with the pesticide panel against the chosen mrlStandard and advances the shipment to RESIDUE_TESTED. The report file is hashed with SHA-256 and anchored.',
    steps: [
      'Validate ResidueTestForm including mrlStandard, labName, reportReference, reportDate and the pesticideResults rows',
      'Apply the MRL gate so PASS sets RESIDUE_TEST_PASSED, FAIL sets RESIDUE_TEST_FAILED and CONDITIONAL_PASS sets RESIDUE_TEST_CONDITIONAL',
      'Hash the report document and store documentS3Key with documentHash',
      'Write the ShipmentEvent with eventType = RESIDUE_TEST_RECORDED and the form as metadata',
      'Set Shipment.currentStatus = RESIDUE_TESTED on a PASS and hold the shipment on a FAIL',
      'Submit a RESIDUE_TEST_RECORDED ChainTransaction and notify the BOILING_UNIT for the next stage',
    ],
  },
  {
    id: 'flow22',
    name: 'Turmeric · Boiling Unit records CURING_COMPLETED',
    trigger: 'BOILING_UNIT submits TurmericCuringForm from its work queue',
    description: 'Records the boiling and curing run as a ShipmentEvent whose metadata is the TurmericCuringForm, and the batch advances without a named ShipmentStatus change. The cured output weight becomes the input for drying.',
    steps: [
      'Verify the shipment sits at RESIDUE_TESTED and the lot is not RESIDUE_TEST_FAILED',
      'Validate TurmericCuringForm including boilingLotId, rawInputWeight, curingMethod, boilingDuration, donenessIndicator and curedOutputWeight',
      'Write the ShipmentEvent with eventType = CURING_COMPLETED and the form as ShipmentEvent.metadata',
      'Carry curedOutputWeight forward as the declared input quantity for the drying stage',
      'Submit an EVENT_RECORDED ChainTransaction and show the ChainBadge amber until finalisation',
      'Move the batch into the DRYING_YARD queue and notify the DRYING_YARD role',
    ],
  },
  {
    id: 'flow23',
    name: 'Turmeric · Drying Yard records DRYING_COMPLETED',
    trigger: 'DRYING_YARD submits TurmericDryingForm from its work queue',
    description: 'Records the drying run with the final moisture content and dried weight as ShipmentEvent.metadata, and the batch advances without a named ShipmentStatus change. A finalMoisture outside the profile band raises a moisture excursion.',
    steps: [
      'Verify the shipment carries a CURING_COMPLETED event and no open handoff dispute',
      'Validate TurmericDryingForm including dryingMethod, completionDate, dryingDays, finalMoisture and driedWeight',
      'Write the ShipmentEvent with eventType = DRYING_COMPLETED and the form as metadata',
      'Compare finalMoisture against the profile band and set hasBreach with breachType = MOISTURE_EXCURSION when it is out of range',
      'Submit an EVENT_RECORDED ChainTransaction, plus a BREACH_RECORDED transaction when an excursion is flagged',
      'Move the batch into the POLISHING_MILL queue and notify the POLISHING_MILL role',
    ],
  },
  {
    id: 'flow24',
    name: 'Turmeric · Polishing Mill records POLISHING_COMPLETED',
    trigger: 'POLISHING_MILL submits TurmericPolishingForm from its work queue',
    description: 'Records the polishing run with input dried weight, output polished weight and grade as ShipmentEvent.metadata, and the batch advances without a named ShipmentStatus change. Polishing loss is derived and stored with the event.',
    steps: [
      'Verify the shipment carries a DRYING_COMPLETED event',
      'Validate TurmericPolishingForm including polishingDate, polishingType, inputDriedKg, outputPolishedKg and grade',
      'Derive polishingLossPct from inputDriedKg and outputPolishedKg when it is not supplied',
      'Write the ShipmentEvent with eventType = POLISHING_COMPLETED and the form as metadata',
      'Submit an EVENT_RECORDED ChainTransaction and update the lot working quantity to outputPolishedKg',
      'Move the batch into the COMMISSION_AGENT mandi queue and notify the COMMISSION_AGENT role',
    ],
  },
  {
    id: 'flow25',
    name: 'Turmeric · Commission Agent records MANDI_FIRST_SALE',
    trigger: 'COMMISSION_AGENT submits TurmericMandiSaleForm at the APMC market yard',
    description: 'Records the first sale at the mandi with the APMC receipt reference as ShipmentEvent.metadata, and the batch advances without a named ShipmentStatus change. This is the provenance link between the farm lot and the processing chain.',
    steps: [
      'Verify the shipment carries a POLISHING_COMPLETED event',
      'Validate TurmericMandiSaleForm including apmcMarketYard, mandiLotNumber, quantitySold, modalSalePrice, buyerTraderName, pattedReceiptNumber and saleDate',
      'Normalise quantitySold from quintal to kg and reconcile it against the polished output',
      'Write the ShipmentEvent with eventType = MANDI_FIRST_SALE and the form as metadata',
      'Submit an EVENT_RECORDED ChainTransaction so the mandi receipt is anchored',
      'Move the batch into the PROCESSING_UNIT queue and notify the PROCESSING_UNIT role',
    ],
  },
  {
    id: 'flow26',
    name: 'Turmeric · Processing Unit records STERILISATION_GRINDING_COMPLETED',
    trigger: 'PROCESSING_UNIT submits TurmericProcessingForm from its work queue',
    description: 'Records sterilisation and grinding with the batch code, grind mesh, curcumin content and packing detail as ShipmentEvent.metadata, and the batch advances without a named ShipmentStatus change. The sterilisation method is carried forward for EU ETO compliance.',
    steps: [
      'Verify the shipment carries a MANDI_FIRST_SALE event',
      'Validate TurmericProcessingForm including batchCode, processingDate, sterilisationMethod, grindMesh, curcuminContent, outputPowderWeight, packingType and packSize',
      'Flag the batch when sterilisationMethod is ETO so the destination MRL check is enforced at the assay stage',
      'Write the ShipmentEvent with eventType = STERILISATION_GRINDING_COMPLETED and the form as metadata',
      'Submit an EVENT_RECORDED ChainTransaction and update the working quantity to outputPowderWeight',
      'Move the batch into the LABORATORY assay queue and notify the LABORATORY role',
    ],
  },
  {
    id: 'flow27',
    name: 'Turmeric · Laboratory records LAB_ASSAY_COMPLETED',
    trigger: 'LABORATORY submits TurmericAssayForm for the processed batch',
    description: 'Records the quality assay covering curcumin, lead chromate, ethylene oxide, aflatoxin B1 and post-process moisture as ShipmentEvent.metadata, and the batch advances without a named ShipmentStatus change. A failing parameter blocks the Spices Board stage.',
    steps: [
      'Verify the shipment carries a STERILISATION_GRINDING_COMPLETED event',
      'Validate TurmericAssayForm including curcuminContent, leadChromate, ethyleneOxide, aflatoxinB1, moisturePostProcess, mrlStandard, labName and reportDate',
      'Fail the assay when leadChromate is Detected or when ethyleneOxide or aflatoxinB1 exceed the chosen mrlStandard limits',
      'Write the ShipmentEvent with eventType = LAB_ASSAY_COMPLETED and the form as metadata',
      'Submit an EVENT_RECORDED ChainTransaction and update the ComplianceMatrix checks for the shipment',
      'Move a passing batch into the SPICES_BOARD_OFFICER queue and notify that role, or hold a failing batch and notify the EXPORTER',
    ],
  },
  {
    id: 'flow28',
    name: 'Turmeric · Spices Board Officer records SPICES_BOARD_REGISTRATION_ISSUED',
    trigger: 'SPICES_BOARD_OFFICER submits TurmericSpicesBoardForm after inspection',
    description: 'Records the Spices Board export certification with the certificate number, CRES or RCMC number and the MRL compliance status as ShipmentEvent.metadata, and the batch advances without a named ShipmentStatus change. The certificate file is anchored as a Certificate record.',
    steps: [
      'Verify the shipment carries a passing LAB_ASSAY_COMPLETED event',
      'Validate TurmericSpicesBoardForm including spicesBoardCertNo, cresRegistrationNo, inspectionDate, issueDate, validUpto, qualityGrade, curcuminVerified and mrlComplianceStatus',
      'Block the stage when mrlComplianceStatus is Non-compliant and notify the EXPORTER',
      'Write the ShipmentEvent with eventType = SPICES_BOARD_REGISTRATION_ISSUED and the form as metadata',
      'Create the Certificate record, hash the uploaded file and submit a CERTIFICATE_ANCHORED ChainTransaction',
      'Move the batch into the EXPORTER booking queue and notify the EXPORTER',
    ],
  },
  {
    id: 'flow29',
    name: 'Turmeric · Exporter records EXPORT_BOOKED',
    trigger: 'EXPORTER submits the export booking form for the certified batch',
    description: 'Records the export booking with the contract number, buyer, destination, incoterm and declared FOB value as ShipmentEvent.metadata, and the batch advances without a named ShipmentStatus change. The booking populates the Shipment commercial fields.',
    steps: [
      'Verify the shipment carries a SPICES_BOARD_REGISTRATION_ISSUED event and the lot is RESIDUE_TEST_PASSED',
      'Validate the booking form including exportContractNo, buyerName, destinationCountry, incoterm, portOfLoading, declaredFobValueUsd and bookingDate',
      'Write destinationCountry, incoterm, declaredFobValueUsd and originPortCode onto the Shipment',
      'Write the ShipmentEvent with eventType = EXPORT_BOOKED and the form as metadata',
      'Submit an EVENT_RECORDED ChainTransaction and run the ComplianceMatrix pre-export check for turmeric',
      'Move the shipment into the FREIGHT_FORWARDER queue and notify the FREIGHT_FORWARDER role',
    ],
  },
  {
    id: 'flow30',
    name: 'Turmeric · Freight Forwarder records FREIGHT_HANDOFF',
    trigger: 'FREIGHT_FORWARDER submits the forwarder handoff form on taking custody',
    description: 'Records the container and booking detail as ShipmentEvent.metadata and sets Shipment.currentStatus = WITH_FORWARDER. This is a custody change, so a two-party HandoffSignature is required.',
    steps: [
      'Verify the shipment carries an EXPORT_BOOKED event and is not DELIVERED or DISPUTE_RESOLVED',
      'Validate the handoff form including bookingNumber, forwarderName, containerNumber, containerType and handoffDate',
      'Create the CustodyTransfer and open a HandoffSignature with the FROM_PARTY signature and the declared quantityKg',
      'Record the receiver decision as HANDOFF_ACCEPTED or HANDOFF_DISPUTED on the same HandoffSignature',
      'Write the ShipmentEvent with eventType = FREIGHT_HANDOFF and set Shipment.currentStatus = WITH_FORWARDER on acceptance',
      'Submit an EVENT_RECORDED plus a CUSTODY_TRANSFERRED ChainTransaction and notify the CUSTOMS_BROKER',
    ],
  },
  {
    id: 'flow31',
    name: 'Turmeric · Customs Broker records CUSTOMS_CLEARED',
    trigger: 'CUSTOMS_BROKER submits the export clearance form with the shipping bill and LEO',
    description: 'Records the shipping bill and Let Export Order as ShipmentEvent.metadata and sets Shipment.currentStatus = CUSTOMS_CLEARED. Customs clearance precedes vessel loading because the LEO is what allows loading.',
    steps: [
      'Verify the shipment sits at WITH_FORWARDER with an accepted HandoffSignature',
      'Validate the clearance form including shippingBillNo, shippingBillDate, portOfLoading and letExportOrderDate',
      'Write the ShipmentEvent with eventType = CUSTOMS_CLEARED and the form as metadata',
      'Set Shipment.currentStatus = CUSTOMS_CLEARED and unlock the vessel loading stage against the LEO date',
      'Submit an EVENT_RECORDED ChainTransaction and anchor the shipping bill document as a Certificate when uploaded',
      'Move the shipment into the SHIPPING_LINE queue and notify the SHIPPING_LINE role',
    ],
  },
  {
    id: 'flow32',
    name: 'Turmeric · Shipping Line records VESSEL_LOADED',
    trigger: 'SHIPPING_LINE submits the vessel loading form with the bill of lading',
    description: 'Records the vessel, voyage and bill of lading as ShipmentEvent.metadata and sets Shipment.currentStatus = VESSEL_LOADED. This is a custody change, so a two-party HandoffSignature is required.',
    steps: [
      'Verify the shipment sits at CUSTOMS_CLEARED with a valid letExportOrderDate on the clearance event',
      'Validate the loading form including vesselName, voyageNumber, billOfLadingNo and loadingDate',
      'Open a HandoffSignature with the FROM_PARTY signature and capture the receiver decision of HANDOFF_ACCEPTED or HANDOFF_DISPUTED',
      'Write vesselName, voyageNumber, actualLoadingDate and etaDestination onto the Shipment',
      'Write the ShipmentEvent with eventType = VESSEL_LOADED and set Shipment.currentStatus = VESSEL_LOADED on acceptance',
      'Submit EVENT_RECORDED and CUSTODY_TRANSFERRED transactions, anchor the bill of lading and notify PORT_ARRIVAL and the BUYER',
    ],
  },
  {
    id: 'flow33',
    name: 'Turmeric · Destination Port records VESSEL_ARRIVED',
    trigger: 'PORT_ARRIVAL submits the arrival form at the discharge port',
    description: 'Records the arrival, outturn quantity and container condition as ShipmentEvent.metadata and sets Shipment.currentStatus = ARRIVED. This is a custody change, so a two-party HandoffSignature is required.',
    steps: [
      'Verify the shipment sits at VESSEL_LOADED or IN_TRANSIT',
      'Validate the arrival form including arrivalDate, dischargePort, outturnQuantityKg and containerCondition',
      'Open a HandoffSignature, compare outturnQuantityKg against the declared quantity and record HANDOFF_ACCEPTED or HANDOFF_DISPUTED',
      'Set Shipment.hasBreach when containerCondition is reefer alarm or seal broken and submit a BREACH_RECORDED transaction',
      'Write the ShipmentEvent with eventType = VESSEL_ARRIVED and set Shipment.currentStatus = ARRIVED',
      'Submit EVENT_RECORDED and CUSTODY_TRANSFERRED transactions and notify IMPORT_CUSTOMS and the BUYER',
    ],
  },
  {
    id: 'flow34',
    name: 'Turmeric · Import Customs records IMPORT_CLEARED',
    trigger: 'IMPORT_CUSTOMS submits the import clearance form at destination',
    description: 'Records the Bill of Entry and examination status as ShipmentEvent.metadata, and the shipment advances without a named ShipmentStatus change. Clearance releases the consignment to the buyer for acceptance.',
    steps: [
      'Verify the shipment sits at ARRIVED with an accepted HandoffSignature from the arrival stage',
      'Validate the clearance form including billOfEntryNo, clearanceDate and examinationStatus',
      'Write the ShipmentEvent with eventType = IMPORT_CLEARED and the form as metadata',
      'Submit an EVENT_RECORDED ChainTransaction and anchor the Bill of Entry document when uploaded',
      'Move the shipment into the BUYER acceptance queue and notify the BUYER and the EXPORTER',
    ],
  },
  {
    id: 'flow35',
    name: 'Turmeric · Overseas Buyer records BUYER_ACCEPTANCE',
    trigger: 'BUYER submits the goods receipt and acceptance form',
    description: 'Records the GRN and received condition as ShipmentEvent.metadata and sets Shipment.currentStatus = DELIVERED. This is the final custody change, so a two-party HandoffSignature closes the chain.',
    steps: [
      'Verify the shipment carries an IMPORT_CLEARED event and is not already DELIVERED or DISPUTE_RESOLVED',
      'Validate the acceptance form including grnNumber, receivedCondition and acceptanceDate',
      'Open a HandoffSignature and record HANDOFF_ACCEPTED, or HANDOFF_DISPUTED when receivedCondition is major damage or short',
      'Write the ShipmentEvent with eventType = BUYER_ACCEPTANCE and set Shipment.currentStatus = DELIVERED on acceptance',
      'Route a HANDOFF_DISPUTED outcome into the dispute flow and set Shipment.currentStatus = DISPUTED instead',
      'Submit EVENT_RECORDED and CUSTODY_TRANSFERRED transactions, lock further recording and notify the EXPORTER and FARMER',
    ],
  },

  /* ═══ C. MANGO PROFILE STATUS MACHINE (Table 16) ══════════════════════ */

  {
    id: 'flow36',
    name: 'Mango · Farmer records LOT_REGISTERED',
    trigger: 'FARMER submits LotRegistrationForm from the orchard on the farmer portal',
    description: 'Registers the orchard harvest as a Lot with the LotRegistrationForm fields and a MangoVariety of ALPHONSO, KESAR, BANGANAPALLI or DASHERI. The lot is created rather than advancing a shipment status.',
    steps: [
      'Validate the LotRegistrationForm required fields including variety, farmName, harvestDate, quantityKg, apedaRegNumber and fssaiLicense',
      'Mint lotId as LOT-MANGO-YYYY-NNNN from commodityKey and set Lot.status = REGISTERED',
      'Capture gpsCoordinates for the orchard when supplied and store it with the lot attributes',
      'Submit a LOT_REGISTERED ChainTransaction and stamp chainTxHash with chainStatus = PENDING',
      'Create the export Shipment for the lot at currentStatus = REGISTERED',
      'Place the lot in the LABORATORY residue-test queue and notify the LABORATORY role',
    ],
  },
  {
    id: 'flow37',
    name: 'Mango · Laboratory records RESIDUE_TEST_RECORDED',
    trigger: 'LABORATORY submits ResidueTestForm for a registered mango lot',
    description: 'Records the ResidueTest pesticide panel against the chosen mrlStandard and advances the shipment to RESIDUE_TESTED. A FAIL blocks the packhouse stage and every stage after it.',
    steps: [
      'Validate ResidueTestForm including mrlStandard, result, labName, reportReference, reportDate and the pesticideResults rows',
      'Apply the MRL gate so PASS sets RESIDUE_TEST_PASSED, FAIL sets RESIDUE_TEST_FAILED and CONDITIONAL_PASS sets RESIDUE_TEST_CONDITIONAL',
      'Hash the lab report with SHA-256 and store documentS3Key with documentHash',
      'Write the ShipmentEvent with eventType = RESIDUE_TEST_RECORDED and the form as metadata',
      'Set Shipment.currentStatus = RESIDUE_TESTED on a PASS and hold the shipment on a FAIL',
      'Submit a RESIDUE_TEST_RECORDED ChainTransaction and notify the PACKHOUSE for the next stage',
    ],
  },
  {
    id: 'flow38',
    name: 'Mango · Packhouse records PACKHOUSE_PROCESSED',
    trigger: 'PACKHOUSE submits MangoPackhouseForm from its work queue',
    description: 'Records grading and packing with accepted and rejected quantities, the grade breakdown and the box count as ShipmentEvent.metadata, and sets Shipment.currentStatus = PACKHOUSE_PROCESSED. The accepted quantity becomes the working quantity for the rest of the chain.',
    steps: [
      'Verify the shipment sits at RESIDUE_TESTED and the lot is RESIDUE_TEST_PASSED',
      'Validate MangoPackhouseForm including acceptedKg, rejectedKg, gradeBreakdown, boxCount and packhouseRegNumber',
      'Reconcile acceptedKg plus rejectedKg against Lot.quantityKg and reject the submission on an unexplained gap',
      'Write the ShipmentEvent with eventType = PACKHOUSE_PROCESSED and set Shipment.currentStatus = PACKHOUSE_PROCESSED',
      'Update the working quantity to acceptedKg and submit an EVENT_RECORDED ChainTransaction',
      'Move the shipment into the TREATMENT_FACILITY queue and notify the TREATMENT_FACILITY role',
    ],
  },
  {
    id: 'flow39',
    name: 'Mango · Treatment Facility records TREATMENT_COMPLETED',
    trigger: 'TREATMENT_FACILITY submits MangoTreatmentForm after the VHT or HWT run',
    description: 'Records vapour heat or hot water treatment against fruit fly with the temperature, duration and core temperature achieved as ShipmentEvent.metadata, and sets Shipment.currentStatus = TREATED. The treatment certificate reference is anchored for the phyto stage.',
    steps: [
      'Verify the shipment sits at PACKHOUSE_PROCESSED',
      'Validate MangoTreatmentForm including treatmentType of VHT or HWT, temperatureCelsius, durationMinutes, coreTemperatureAchieved and certificateReference',
      'Reject the run when coreTemperatureAchieved or durationMinutes fall short of the fruit fly protocol for the destination market',
      'Write the ShipmentEvent with eventType = TREATMENT_COMPLETED and set Shipment.currentStatus = TREATED',
      'Create the TREATMENT Certificate from certificateReference and submit a CERTIFICATE_ANCHORED ChainTransaction',
      'Submit an EVENT_RECORDED ChainTransaction and notify the NPPO_INSPECTOR for the phytosanitary stage',
    ],
  },
  {
    id: 'flow40',
    name: 'Mango · NPPO Inspector records PHYTO_CERTIFICATE_ISSUED',
    trigger: 'NPPO_INSPECTOR submits the phytosanitary certificate form after inspection',
    description: 'Records the phytosanitary certificate number, issue date, validity date and pest findings as ShipmentEvent.metadata, and sets Shipment.currentStatus = PHYTO_CLEARED. The certificate PDF is hashed and anchored.',
    steps: [
      'Verify the shipment sits at TREATED with an anchored treatment certificate',
      'Validate the phyto form including certificateNumber, issueDate, validityDate and pestFindings',
      'Block the stage when pestFindings is not clear and notify the EXPORTER and PLATFORM_ADMIN',
      'Create the PHYTOSANITARY Certificate, hash the file with SHA-256 and submit a CERTIFICATE_ANCHORED ChainTransaction',
      'Write the ShipmentEvent with eventType = PHYTO_CERTIFICATE_ISSUED and set Shipment.currentStatus = PHYTO_CLEARED',
      'Submit an EVENT_RECORDED ChainTransaction and notify the APEDA_OFFICER for the certificate of origin',
    ],
  },
  {
    id: 'flow41',
    name: 'Mango · APEDA Officer records COO_ISSUED',
    trigger: 'APEDA_OFFICER submits the certificate of origin form',
    description: 'Records the COO number, issue date and HS code as ShipmentEvent.metadata, and sets Shipment.currentStatus = APEDA_CERTIFIED. The HS code is written onto the Shipment for the customs stage.',
    steps: [
      'Verify the shipment sits at PHYTO_CLEARED',
      'Validate the COO form including certificateNumber, issueDate and hsCode',
      'Write hsCode onto the Shipment so the customs broker files against it',
      'Create the CERTIFICATE_OF_ORIGIN Certificate, hash the file and submit a CERTIFICATE_ANCHORED ChainTransaction',
      'Write the ShipmentEvent with eventType = COO_ISSUED and set Shipment.currentStatus = APEDA_CERTIFIED',
      'Submit an EVENT_RECORDED ChainTransaction and keep the shipment in the APEDA_OFFICER queue for export inspection',
    ],
  },
  {
    id: 'flow42',
    name: 'Mango · APEDA Officer records EXPORT_INSPECTION_ISSUED',
    trigger: 'APEDA_OFFICER submits the export inspection form after drawing the sample',
    description: 'Records the EIC number, inspection date, sample size and results summary as ShipmentEvent.metadata, and the shipment advances without a named ShipmentStatus change. The EIC completes the APEDA compliance pair before customs.',
    steps: [
      'Verify the shipment sits at APEDA_CERTIFIED with an anchored certificate of origin',
      'Validate the export inspection form including certificateNumber, inspectionDate, sampleSize and resultsSummary',
      'Create the EXPORT_INSPECTION Certificate, hash the file and submit a CERTIFICATE_ANCHORED ChainTransaction',
      'Write the ShipmentEvent with eventType = EXPORT_INSPECTION_ISSUED and the form as metadata',
      'Submit an EVENT_RECORDED ChainTransaction and mark the ComplianceMatrix export checks satisfied',
      'Move the shipment into the CUSTOMS_BROKER queue and notify the CUSTOMS_BROKER role',
    ],
  },
  {
    id: 'flow43',
    name: 'Mango · Customs Broker records CUSTOMS_CLEARED',
    trigger: 'CUSTOMS_BROKER submits the export clearance form with the shipping bill and LEO',
    description: 'Records the shipping bill, LEO number and date and the ICEGATE reference as ShipmentEvent.metadata, and sets Shipment.currentStatus = CUSTOMS_CLEARED. The LEO is what allows the later vessel loading.',
    steps: [
      'Verify the shipment carries both COO_ISSUED and EXPORT_INSPECTION_ISSUED events',
      'Validate the customs form including shippingBillNumber, shippingBillDate, leoDate, leoNumber and icegateReference',
      'Write the ShipmentEvent with eventType = CUSTOMS_CLEARED and set Shipment.currentStatus = CUSTOMS_CLEARED',
      'Record the LEO date as the precondition that unlocks the VESSEL_LOADED stage',
      'Submit an EVENT_RECORDED ChainTransaction and anchor the shipping bill document when uploaded',
      'Move the shipment into the COLD_STORAGE queue and notify the COLD_STORAGE role',
    ],
  },
  {
    id: 'flow44',
    name: 'Mango · Cold Storage records COLD_STORAGE_ENTRY',
    trigger: 'COLD_STORAGE submits the reefer custody form on intake',
    description: 'Records the facility, target temperature band, entry temperature and pallet count as ShipmentEvent.metadata, and sets Shipment.currentStatus = IN_COLD_STORAGE. Entry starts the reefer telemetry stream for breach detection.',
    steps: [
      'Verify the shipment sits at CUSTOMS_CLEARED',
      'Validate the cold storage form including facilityName, targetTempMinCelsius, targetTempMaxCelsius, actualTempAtEntry and palletCount',
      'Bind the facility IotDevice records to the shipment and open the TelemetryReading stream against the target band',
      'Write the ShipmentEvent with eventType = COLD_STORAGE_ENTRY and set Shipment.currentStatus = IN_COLD_STORAGE',
      'Submit an EVENT_RECORDED ChainTransaction and surface the live stream on the shipment telemetry tab',
      'Arm breach detection so an excursion sets hasBreach and breachType and records BREACH_RECORDED',
    ],
  },
  {
    id: 'flow45',
    name: 'Mango · Freight Forwarder records CUSTODY_TRANSFER',
    trigger: 'FREIGHT_FORWARDER submits the custody transfer form on collection from cold storage',
    description: 'Records the transferring and receiving organisations, the location, quantity and condition notes as ShipmentEvent.metadata, and sets Shipment.currentStatus = WITH_FORWARDER. This is a custody change, so a two-party HandoffSignature is required.',
    steps: [
      'Verify the shipment sits at IN_COLD_STORAGE and is not DELIVERED or DISPUTE_RESOLVED',
      'Validate the custody transfer form including fromOrganisation, toOrganisation, location, quantityKg and conditionNotes',
      'Create the CustodyTransfer and open a HandoffSignature with the FROM_PARTY signature and the declared quantityKg',
      'Record the receiver decision as HANDOFF_ACCEPTED or HANDOFF_DISPUTED on the same HandoffSignature',
      'Write the ShipmentEvent with eventType = CUSTODY_TRANSFER and set Shipment.currentStatus = WITH_FORWARDER on acceptance',
      'Submit EVENT_RECORDED and CUSTODY_TRANSFERRED transactions, carry the telemetry stream forward and notify the SHIPPING_LINE',
    ],
  },
  {
    id: 'flow46',
    name: 'Mango · Shipping Line records VESSEL_LOADED',
    trigger: 'SHIPPING_LINE submits the vessel loading form with the bill of lading',
    description: 'Records the vessel, voyage, bill of lading and the loading and discharge ports as ShipmentEvent.metadata, and sets Shipment.currentStatus = VESSEL_LOADED. This is a custody change, so a two-party HandoffSignature is required.',
    steps: [
      'Verify the shipment sits at WITH_FORWARDER and the customs event carries a valid leoDate',
      'Validate the loading form including vesselName, voyageNumber, blNumber, portOfLoading, portOfDischarge and eta',
      'Open a HandoffSignature and record the receiver decision of HANDOFF_ACCEPTED or HANDOFF_DISPUTED',
      'Write vesselName, voyageNumber, actualLoadingDate and etaDestination onto the Shipment',
      'Write the ShipmentEvent with eventType = VESSEL_LOADED and set Shipment.currentStatus = VESSEL_LOADED on acceptance',
      'Submit EVENT_RECORDED and CUSTODY_TRANSFERRED transactions, anchor the bill of lading and keep reefer telemetry running in transit',
    ],
  },
  {
    id: 'flow47',
    name: 'Mango · Overseas Buyer records BUYER_ARRIVAL',
    trigger: 'BUYER submits the arrival form at the port of discharge',
    description: 'Records the arrival date, port of discharge and import inspection findings as ShipmentEvent.metadata, and sets Shipment.currentStatus = ARRIVED. This is a custody change, so a two-party HandoffSignature is required.',
    steps: [
      'Verify the shipment sits at VESSEL_LOADED or IN_TRANSIT',
      'Validate the arrival form including arrivalDate, portOfDischarge and importInspectionFindings',
      'Open a HandoffSignature, review the declared quantity against what arrived and record HANDOFF_ACCEPTED or HANDOFF_DISPUTED',
      'Close the reefer telemetry stream and fold any recorded excursion into Shipment.complianceScore',
      'Write the ShipmentEvent with eventType = BUYER_ARRIVAL and set Shipment.currentStatus = ARRIVED',
      'Submit EVENT_RECORDED and CUSTODY_TRANSFERRED transactions and notify the EXPORTER and FREIGHT_FORWARDER',
    ],
  },
  {
    id: 'flow48',
    name: 'Mango · Overseas Buyer records BUYER_ACCEPTANCE',
    trigger: 'BUYER submits the acceptance form after inspecting the consignment',
    description: 'Records the acceptance date and condition notes as ShipmentEvent.metadata and sets Shipment.currentStatus = DELIVERED. This is the final custody change, and a rejection routes into the dispute flow instead.',
    steps: [
      'Verify the shipment sits at ARRIVED and is not already DELIVERED or DISPUTE_RESOLVED',
      'Validate the acceptance form including acceptanceDate and conditionNotes',
      'Open a HandoffSignature and record HANDOFF_ACCEPTED, or HANDOFF_DISPUTED when the buyer rejects the consignment',
      'Write the ShipmentEvent with eventType = BUYER_ACCEPTANCE and set Shipment.currentStatus = DELIVERED on acceptance',
      'Route a HANDOFF_DISPUTED outcome into the dispute flow with Shipment.currentStatus = DISPUTED',
      'Submit EVENT_RECORDED and CUSTODY_TRANSFERRED transactions, lock further recording and publish the completed journey to Public Verify',
    ],
  },
];

module.exports = { FLOWS };
