/* ═══════════════════════════════════════════════════════════════════ */
/*  AquaTrace - STEP 2 BEHAVIOUR · LOGIC (52 flows)                    */
/*  Ground truth: scripts/aquatrace/SPEC.md                            */
/*    A. AquaChain & platform ....... flow01–flow20                    */
/*    B. Monitoring rules (TABLE 72)  flow21–flow25                    */
/*    C. Stage flows (TABLE 42/43) .. flow26–flow50                    */
/*    D. Cross-cutting surface ...... flow51–flow52                    */
/* ═══════════════════════════════════════════════════════════════════ */

const FLOWS = [
  /* ───────── A. AquaChain & platform ───────── */
  {
    id: 'flow01',
    name: 'AquaChain · Sign and hash every event',
    trigger: 'Any actor submits a form for an entity flagged anchoredOnChain',
    description: 'The event payload is canonicalised and hashed with SHA-256, then signed with the acting party ed25519 key held in ChainKeypair. A ChainTransaction is written with status PENDING until a block confirms it.',
    steps: [
      'Build the canonical event payload for the anchored entity and its transaction type key',
      'Compute the SHA-256 digest over the canonical payload',
      'Decrypt the actor ed25519 private key from ChainKeypair and sign the digest',
      'Create a ChainTransaction carrying the type key, payload digest and signature with status PENDING',
      'Queue the transaction in the pending pool for the next block',
    ],
  },
  {
    id: 'flow02',
    name: 'AquaChain · Block production every BLOCK_INTERVAL_MS',
    trigger: 'The producer node timer fires at BLOCK_INTERVAL_MS (5000 ms) while transactions are pending',
    description: 'The producer seals a block every 5000 ms whenever ChainTransaction rows are pending, batching them under a Merkle root. The new ChainBlock carries previousHash and its computed blockHash so the chain stays hash-linked.',
    steps: [
      'Collect every ChainTransaction still in PENDING from the pool',
      'Compute the Merkle root over the batched transaction digests',
      'Read previousHash from the current head ChainBlock',
      'Seal a new ChainBlock with the Merkle root, previousHash and computed blockHash',
      'Broadcast the sealed block to the validator set for co-signing',
    ],
  },
  {
    id: 'flow03',
    name: 'AquaChain · Validator co-sign and finality at 4 of 5',
    trigger: 'A sealed ChainBlock is broadcast to the validator set',
    description: 'Each of the CONSENSUS_VALIDATOR_COUNT (5) ValidatorNode entries signs the blockHash and writes a ValidatorSignature. The block reaches FINALISED at CONSENSUS_THRESHOLD (4) signatures and its transactions flip to CONFIRMED.',
    steps: [
      'Distribute the sealed blockHash to all 5 ValidatorNode entries',
      'Each validator re-checks the Merkle root and the previousHash link before voting',
      'Record one ValidatorSignature per validator vote',
      'Mark the ChainBlock FINALISED once 4 of 5 signatures are present',
      'Set every ChainTransaction in the block to CONFIRMED and advance the head block',
    ],
  },
  {
    id: 'flow04',
    name: 'AquaChain · Per-actor key custody under CHAIN_MASTER_KEY',
    trigger: 'An invited user accepts an invitation and their actor record is created',
    description: 'An ed25519 keypair is generated for the actor and stored as a ChainKeypair. The private key is encrypted at rest with the 32-byte MasterKey (CHAIN_MASTER_KEY) and decrypted only in memory to sign an event.',
    steps: [
      'Generate an ed25519 keypair for the accepting actor',
      'Encrypt the private key with the 32-byte CHAIN_MASTER_KEY held as MasterKey',
      'Store the ChainKeypair with the public key kept in the clear',
      'Bind the public key to the actor so any ChainTransaction signature can be verified',
      'Decrypt the private key in memory only for the duration of a signing call',
    ],
  },
  {
    id: 'flow05',
    name: 'Handoff · Two-party custody transfer with receiver co-signature',
    trigger: 'A stage that declares a handoff is submitted by the sending role',
    description: 'The TraceUnit moves into the receiving role incoming queue with handoffStatus AWAITING_ACCEPTANCE, and a HandoffAgreement holds the sender ed25519 signature over the declared fields. The receiver co-signs to reach ACCEPTED or flags a discrepancy to reach DISPUTED.',
    steps: [
      'Create a HandoffAgreement carrying the declared fields named in the stage definition',
      'Sign the declared fields with the sender ed25519 key and set status AWAITING_ACCEPTANCE',
      'Set TraceUnit.handoffStatus to AWAITING_ACCEPTANCE and route the unit to the receiving role incoming queue',
      'On accept_handoff, store the receiver ed25519 signature and set the agreement ACCEPTED',
      'On flag_discrepancy, set the agreement DISPUTED, open a Dispute and place a LotHold where the quantity or lot reference is contested',
      'Notify both parties of the outcome',
    ],
  },
  {
    id: 'flow06',
    name: 'Pipeline · Stage prerequisite gate',
    trigger: 'A role opens a work queue entry for a stage that declares a Requires transaction',
    description: 'A stage becomes actionable only once its Requires transaction (TABLE 42 farmed, TABLE 43 wild) already exists on the TraceUnit. Until then the form stays locked and any direct submission is rejected.',
    steps: [
      'Read currentStageKey and pipelinePointer from the TraceUnit',
      'Look up the Requires transaction key declared for the stage',
      'Search the unit ChainTransaction history for a confirmed transaction of that key',
      'Keep the stage form locked and out of the work queue while the prerequisite is missing',
      'Reject any direct submission with a prerequisite error and log the blocked StageTransition attempt',
    ],
  },
  {
    id: 'flow07',
    name: 'Pipeline · Repeatable stages never advance the pipeline pointer',
    trigger: 'A repeatable stage form is submitted: stage_growout, stage_sampling, stage_input_application, stage_onvessel_processing or stage_transhipment',
    description: 'A repeatable stage can be recorded many times against the same TraceUnit and anchors a fresh transaction on each submission. The pipelinePointer and currentStageKey are left untouched so the stage stays open for the next reading.',
    steps: [
      'Confirm the stage is marked repeatable in the profile pipeline definition',
      'Anchor the submitted event as a new ChainTransaction on the unit',
      'Append a StageTransition entry recording the repeat occurrence',
      'Leave TraceUnit.pipelinePointer and TraceUnit.currentStageKey unchanged',
      'Keep the stage in the role work queue so it can be recorded again',
    ],
  },
  {
    id: 'flow08',
    name: 'Laboratory · Derive result_pass from residue value against limit',
    trigger: 'A plant_quality_manager submits a LabReport (tx_lab_result)',
    description: 'The pass flag is derived rather than typed: result_pass is true when residue_value is less than or equal to residue_limit for the tested substance. A breach sets result_pass false and feeds the residue monitoring rule.',
    steps: [
      'Validate sample_id, source_lot_ref, substance, tested_on and laboratory are present',
      'Check residue_value and residue_limit are numeric and not negative',
      'Set result_pass true when residue_value is less than or equal to residue_limit, otherwise false',
      'Sign and submit tx_lab_result anchoring the LabReport against source_lot_ref',
      'Pass a failing result to rule_residue_breach for alerting and lot hold',
      'Publish the derived result to the record detail and the public verify view',
    ],
  },
  {
    id: 'flow09',
    name: 'Compliance · Certificate mandate and public verify scorecard',
    trigger: 'A consignment reaches stage_export_documentation or a public verify page is rendered',
    description: 'Every mandatory certificate type for the active profile (TABLE 40) must be anchored for a shipment to score fully compliant. The ComplianceScorecard reports each CertificateMandate as satisfied or missing.',
    steps: [
      'Resolve the mandatory certificate keys for the profile from CertificateMandate',
      'Check an anchored Certificate exists for each mandatory key against the correct subject entity',
      'Add the destination-conditional mandates cert_catch and cert_mpeda_enrolment when destination is european_union',
      'Score each mandate satisfied or missing on the ComplianceScorecard',
      'Surface the scorecard on the record detail and on the public verify page',
    ],
  },
  {
    id: 'flow10',
    name: 'Compliance · Issue a certificate and anchor a document',
    trigger: 'An exporter_administrator issues a Certificate or anchors a supporting DocumentAnchor',
    description: 'tx_certificate writes the Certificate with certificate_number, anchored_lot_ref, issuer, issued_on, valid_until and document_digest, while tx_document_anchor writes a DocumentAnchor for any other document. Only the digest is anchored, never the file itself.',
    steps: [
      'Validate certificate_number, anchored_lot_ref, issuer, issued_on and document_digest',
      'Compute or accept the SHA-256 document_digest for the supporting file',
      'Sign and submit tx_certificate or tx_document_anchor against the TraceUnit',
      'Refresh the CertificateMandate status for the subject entity on the ComplianceScorecard',
      'Notify the exporter_administrator and any regulator_auditor watching the unit',
    ],
  },
  {
    id: 'flow11',
    name: 'Lots · Split and merge preserving parent and child lot references',
    trigger: 'A role holding record_event on lot_transform_event submits a LotTransformEvent',
    description: 'tx_split and tx_merge anchor a LotTransformEvent carrying operation, input_lots, output_lots and unit. Parent and child lot references are preserved so the chain of custody stays walkable in both directions.',
    steps: [
      'Validate operation, unit, input_lots and output_lots are populated',
      'Confirm every input lot already exists on the TraceUnit history',
      'Sign and submit tx_split or tx_merge depending on the declared operation',
      'Write the parent-to-child lot links so downstream events resolve back to their origin',
      'Render the branch or join on the record detail chain-of-custody timeline',
    ],
  },
  {
    id: 'flow12',
    name: 'Public · Verify a shipment at /verify/:code with no account',
    trigger: 'A consumer opens /verify and types the code, or scans the QR printed on the record',
    description: 'The public page resolves TraceUnit.publicVerifyCode and renders the full chain of custody, the compliance scorecard, the anchored certificates and the lab results. No authentication is required and nothing outside that shipment is exposed.',
    steps: [
      'Resolve the submitted code against TraceUnit.publicVerifyCode',
      'Load the ordered on-chain event timeline for the unit',
      'Attach the ComplianceScorecard, anchored Certificate records and LabReport results',
      'Render the read-only page at /verify/:code with no account and no write actions',
      'Serve the same view from the QR link aquatrace.cerulea.io/verify/<shipment-code>',
    ],
  },
  {
    id: 'flow13',
    name: 'Explorer · End-to-end chain re-verification',
    trigger: 'An authenticated user opens /explorer or starts a verification run',
    description: 'The explorer lists finalized blocks, confirmed and pending transactions and the head block, then walks the chain re-checking every hash link, Merkle root and validator signature. The outcome is stored as a ChainVerificationRun.',
    steps: [
      'Load the finalized ChainBlock list, the pending ChainTransaction pool and the head block',
      'Recompute each blockHash and confirm it matches the previousHash of the next block',
      'Recompute each Merkle root against the block transaction digests',
      'Verify every ValidatorSignature against its ValidatorNode public key and count votes against the threshold of 4',
      'Store the outcome as a ChainVerificationRun and show recent blocks with their hashes and validator votes',
    ],
  },
  {
    id: 'flow14',
    name: 'Access · Enforce {action · entity} RBAC grants per role',
    trigger: 'Any API call that creates, reads, updates, accepts a handoff, flags a discrepancy, issues a certificate, records an event or verifies',
    description: 'Each role holds a list of {action · entity} grants over create, read, update, accept_handoff, flag_discrepancy, issue_certificate, record_event and verify, where entity "*" means any entity. regulator_auditor holds verify plus read only and can never advance the workflow.',
    steps: [
      'Resolve the caller role and its grant list from the role definitions in TABLE 41',
      'Match the requested action and target entity against the grants, treating "*" as any entity',
      'Deny the call and record the refusal when no grant matches',
      'Hide stage forms and handoff actions the role cannot perform from the dashboard',
      'Restrict regulator_auditor to verify and read so it can write no StageTransition',
    ],
  },
  {
    id: 'flow15',
    name: 'Access · Tenant isolation and one profile per normal user',
    trigger: 'A user signs in and any scoped query is issued',
    description: 'Every Organisation and its records are scoped to a tenant, and a normal user is bound to exactly one profile, farmed_aquaculture or wild_capture. platform_admin may switch between profiles and platform_super_admin additionally manages users and system settings.',
    steps: [
      'Resolve the tenant and the bound profile from the AuthSession',
      'Apply the tenant filter to every record, TraceUnit and chain query',
      'Reject any cross-tenant identifier supplied in a request path or body',
      'Let platform_admin switch the active profile from /admin while staying inside the tenant',
      'Let platform_super_admin manage users, roles, invitations and system settings in addition',
    ],
  },
  {
    id: 'flow16',
    name: 'Auth · JWT lifetimes, TOTP MFA and rate limiting',
    trigger: 'A user posts credentials at /login',
    description: 'A successful sign-in issues a 900 s access token and a 1,209,600 s refresh token into an AuthSession, prompting for the TOTP code when an MfaEnrolment exists under the issuer label "AquaTrace". Requests are limited to 120 per 60 s window.',
    steps: [
      'Verify email and password and look for an active MfaEnrolment',
      'Prompt for the TOTP code and validate it against the "AquaTrace" issuer secret',
      'Issue an access token valid 900 s and a refresh token valid 1,209,600 s',
      'Open an AuthSession bound to the tenant, profile and role',
      'Count the request against the RateLimitBucket and reject beyond 120 requests per 60 s',
    ],
  },
  {
    id: 'flow17',
    name: 'Onboarding · Accept an invitation at /accept-invite',
    trigger: 'An invited user opens the tokenised /accept-invite link',
    description: 'The Invitation token is validated, the user sets a password, and the account joins the named Organisation with the invited role. Acceptance also provisions the actor ChainKeypair used to sign every later event.',
    steps: [
      'Validate the Invitation token and confirm it is unexpired and unused',
      'Collect and store the new password for the user',
      'Attach the user to the invited Organisation, tenant and role',
      'Provision the ed25519 ChainKeypair encrypted with CHAIN_MASTER_KEY',
      'Mark the Invitation consumed and land the user on /dashboard',
    ],
  },
  {
    id: 'flow18',
    name: 'Dashboard · Role workspace at /dashboard',
    trigger: 'An authenticated user opens /dashboard',
    description: 'The workspace renders KPI tiles, the chain-verified banner, live alerts, incoming custody handoffs to accept or dispute, the work queue for the next step or lab result, and the origin-create or supply form where the role owns one. Everything is filtered by the role grants and the bound profile.',
    steps: [
      'Load KPI tiles across the TraceUnit rows in the user scope',
      'Show the chain-verified banner from the latest ChainVerificationRun',
      'List open Alert rows raised by the monitoring rules',
      'List HandoffAgreement rows in AWAITING_ACCEPTANCE addressed to this role with accept and flag actions',
      'Build the work queue from the stages the role performs whose Requires transaction is already present',
      'Expose the origin-create form for broodstock_multiplication_centre or skipper where applicable',
    ],
  },
  {
    id: 'flow19',
    name: 'Notifications · Stage events, handoffs, alerts and disputes',
    trigger: 'A StageTransition, HandoffAgreement status change, Alert or Dispute is written',
    description: 'A Notification is created for the parties who need to act: the next role on a handoff, the recording role on a stage event, and the affected parties on an alert or dispute. Read-only regulator_auditor recipients are notified without an action link.',
    steps: [
      'Classify the event as a stage event, a handoff, an alert or a dispute',
      'Resolve recipient roles from the pipeline definition and the role grants',
      'Create a Notification per recipient carrying the record link and the required action',
      'Surface unread notifications in the /dashboard header and alert panel',
      'Suppress action links for regulator_auditor recipients',
    ],
  },
  {
    id: 'flow20',
    name: 'Localisation · Locale fallback, per-profile terminology and palette',
    trigger: 'A page renders for a user with a locale and a bound profile',
    description: 'Labels resolve against the supported locales en, te, ta, ml, or, bn, gu, mr and kn, and any missing key falls back to English. The active profile then applies its terminology overrides and palette so the same screens read as Broodstock lot, Pond and Farmer or as Fishing trip, Vessel and Skipper.',
    steps: [
      'Resolve the user locale from the supported list and fall back to en for any missing key',
      'Load the profile terminology overrides for origin_unit, lot, producer, facility, harvest and handoff',
      'Rename core terms in place, for example origin_unit to Broodstock lot on farmed and Fishing trip on wild',
      'Apply the profile palette and logo, teal #0f766e for farmed and blue #0369a1 for wild',
      'Render localised profile names such as saagaru saagu for te and kaadu meen pidippu for ta',
    ],
  },

  /* ───────── B. Monitoring rules (TABLE 72) ───────── */
  {
    id: 'flow21',
    name: 'Alert · rule_dissolved_oxygen_low on growout_reading.dissolved_oxygen',
    trigger: 'A farmer submits a GrowoutReading carrying a dissolved_oxygen value',
    description: 'The MonitoringRule fires when growout_reading.dissolved_oxygen is less than 4 mg/L. An Alert is raised against the CropCycle warning that the crop is under a stress threshold.',
    steps: [
      'Read dissolved_oxygen from the submitted GrowoutReading',
      'Evaluate the lt comparison against the threshold of 4 mg/L',
      'Raise an Alert keyed rule_dissolved_oxygen_low carrying "Dissolved oxygen has fallen below 4 mg/L, a stress threshold for the crop."',
      'Attach the alert to the CropCycle and its TraceUnit timeline',
      'Notify the farmer and show the alert on the role workspace alert panel',
    ],
  },
  {
    id: 'flow22',
    name: 'Alert · rule_ammonia_high on growout_reading.ammonia',
    trigger: 'A farmer submits a GrowoutReading carrying an ammonia value',
    description: 'The MonitoringRule fires when growout_reading.ammonia is greater than 0.1 mg/L. An Alert is raised against the CropCycle flagging a water quality problem in the pond.',
    steps: [
      'Read ammonia from the submitted GrowoutReading',
      'Evaluate the gt comparison against the threshold of 0.1 mg/L',
      'Raise an Alert keyed rule_ammonia_high carrying "Ammonia has risen above 0.1 mg/L, indicating a water quality problem."',
      'Attach the alert to the CropCycle and its TraceUnit timeline',
      'Notify the farmer and any regulator_auditor watching the unit',
    ],
  },
  {
    id: 'flow23',
    name: 'Alert · rule_residue_breach on lab_report.residue_value with lot hold',
    trigger: 'A LabReport is submitted on either profile with residue_value above residue_limit',
    description: 'The MonitoringRule fires when lab_report.residue_value exceeds the per-substance residue_limit. The alert message requires the affected lot to be held, so a LotHold is placed and the unit stops advancing.',
    steps: [
      'Read residue_value and residue_limit from the submitted LabReport',
      'Evaluate the gt comparison against the per-substance residue_limit',
      'Raise an Alert keyed rule_residue_breach carrying "A residue reading has exceeded its maximum residue limit. The affected lot must be held."',
      'Place a LotHold on source_lot_ref and block further stage submissions on the TraceUnit',
      'Mark the affected lot non-compliant on the ComplianceScorecard',
      'Notify the plant_quality_manager, the exporter_administrator and any regulator_auditor',
    ],
  },
  {
    id: 'flow24',
    name: 'Alert · rule_input_not_certified on input_application_event.caa_certified',
    trigger: 'A farmer submits an InputApplicationEvent with caa_certified recorded false',
    description: 'The MonitoringRule fires on the eq 0 comparison when caa_certified is false. The alert flags an input outside the Coastal Aquaculture Authority certified list and puts the cert_coc_inputs mandate at risk.',
    steps: [
      'Read caa_certified from the submitted InputApplicationEvent',
      'Evaluate the eq comparison against 0, meaning the input is not certified',
      'Raise an Alert keyed rule_input_not_certified carrying "An input was applied that is not on the Coastal Aquaculture Authority certified list."',
      'Flag the cert_coc_inputs mandate as at risk on the ComplianceScorecard',
      'Notify the farmer and the exporter_administrator handling the downstream consignment',
    ],
  },
  {
    id: 'flow25',
    name: 'Alert · rule_transport_temperature on transport_event.temperature_max',
    trigger: 'A transporter submits a TransportEvent carrying a temperature_max reading',
    description: 'The MonitoringRule fires on both profiles when transport_event.temperature_max is greater than 4 C. The alert records a first-mile or transport excursion outside the chilled range for iced product.',
    steps: [
      'Read temperature_max and logger_fitted from the submitted TransportEvent',
      'Skip evaluation when logger_fitted is false and no temperature was captured',
      'Evaluate the gt comparison against the threshold of 4 C',
      'Raise an Alert keyed rule_transport_temperature carrying "The transport leg exceeded 4 C, outside the chilled range for iced product."',
      'Notify the transporter and the receiving role on lot_ref and pin the excursion to the unit timeline',
    ],
  },

  /* ───────── C. Stage flows · Farmed Aquaculture (TABLE 42) ───────── */
  {
    id: 'flow26',
    name: 'Farmed · Broodstock multiplication centre records tx_broodstock (BroodstockEvent)',
    trigger: 'A broodstock_multiplication_centre submits the Broodstock lot form at stage_broodstock',
    description: 'Emits tx_broodstock, an origin_create transaction with no prerequisite, creating the TraceUnit whose origin unit is the BroodstockEvent. Not repeatable; hands off to hatchery_operator declaring broodstock_lot and species.',
    steps: [
      'Validate broodstock_lot, source_centre, centre_registration, species, spf_status, spf_panel, screening_method, screening_laboratory, health_certificate_number, screened_on, broodstock_count (min 0) and supply_date',
      'Sign the canonical payload with the centre ed25519 key',
      'Submit tx_broodstock and create the TraceUnit with its publicVerifyCode and currentStageKey stage_broodstock',
      'Advance the pipelinePointer to stage_hatchery',
      'Open a HandoffAgreement to hatchery_operator declaring broodstock_lot and species, unit AWAITING_ACCEPTANCE',
      'Notify the hatchery_operator incoming queue',
    ],
  },
  {
    id: 'flow27',
    name: 'Farmed · Hatchery operator records tx_hatchery (HatcheryEvent)',
    trigger: 'A hatchery_operator accepts the broodstock handoff and submits the Hatchery dispatch form at stage_hatchery',
    description: 'Emits tx_hatchery and requires tx_broodstock on the unit. Not repeatable; advances the pointer to stage_stocking and hands off to farmer declaring seed_lot and seed_quantity.',
    steps: [
      'Confirm tx_broodstock exists on the TraceUnit and co-sign the incoming HandoffAgreement as ACCEPTED or flag a discrepancy',
      'Validate seed_lot, broodstock_source, tank_harvest_date, hatchery_registration, post_larval_stage, seed_quantity (min 0), broodstock_health_status, seed_screening_result, pathogen_panel, screening_method, screening_laboratory, seed_health_certificate_number, screened_on and destination_farm',
      'Sign and submit tx_hatchery against the unit',
      'Advance the pipelinePointer to stage_stocking',
      'Open a HandoffAgreement to farmer declaring seed_lot and seed_quantity',
      'Notify the destination_farm farmer incoming queue',
    ],
  },
  {
    id: 'flow28',
    name: 'Farmed · Farmer records tx_stocking (CropCycle)',
    trigger: 'A farmer accepts the hatchery handoff and submits the Pond stocking form at stage_stocking',
    description: 'Emits tx_stocking and requires tx_hatchery, opening the CropCycle that parents every later farmed event. No handoff; the pointer moves into the grow-out block that the same farmer owns.',
    steps: [
      'Confirm tx_hatchery exists and the incoming HandoffAgreement is ACCEPTED',
      'Validate crop_code, pond_id, farm_registration, mpeda_enrolment, species, farming_method, pond_position, seed_source_lot, stocking_date, seed_quantity (min 0) and stocking_density (min 0)',
      'Check the cert_caa_unit registration is anchored against the crop cycle',
      'Sign and submit tx_stocking against the unit',
      'Advance the pipelinePointer to stage_input_application and unlock stage_growout and stage_sampling',
      'Notify the farmer that the crop cycle is open on chain',
    ],
  },
  {
    id: 'flow29',
    name: 'Farmed · Farmer records tx_input_application (InputApplicationEvent)',
    trigger: 'A farmer submits the Feed and input application form at stage_input_application',
    description: 'Emits tx_input_application and requires tx_stocking, anchored under the CropCycle. Repeatable with no handoff, so the pipeline pointer does not move.',
    steps: [
      'Confirm tx_stocking exists on the TraceUnit',
      'Validate input_type, product_name, product_batch, caa_certified, quantity (min 0) and applied_on',
      'Sign and submit tx_input_application against the crop cycle',
      'Evaluate rule_input_not_certified on the submitted caa_certified flag',
      'Leave the pipelinePointer unchanged and keep the repeatable stage in the farmer work queue',
    ],
  },
  {
    id: 'flow30',
    name: 'Farmed · Farmer records tx_growout (GrowoutReading)',
    trigger: 'A farmer submits the Grow-out reading form at stage_growout',
    description: 'Emits tx_growout and requires tx_stocking, capturing the tracked quality parameters salinity, dissolved_oxygen, ph, ammonia and estimated_body_weight. Repeatable with no handoff, so the pointer stays where it is.',
    steps: [
      'Confirm tx_stocking exists on the TraceUnit',
      'Validate reading_date and mortality_observed, and range-check ph between 0 and 14',
      'Sign and submit tx_growout against the crop cycle',
      'Evaluate rule_dissolved_oxygen_low and rule_ammonia_high on the submitted reading',
      'Record the readings as quality parameters and leave the pipelinePointer unchanged',
    ],
  },
  {
    id: 'flow31',
    name: 'Farmed · Farmer records tx_sampling (SamplingEvent)',
    trigger: 'A farmer submits the Pre-harvest sampling form at stage_sampling',
    description: 'Emits tx_sampling and requires tx_stocking, sealing a sample for laboratory residue testing. Repeatable with no handoff.',
    steps: [
      'Confirm tx_stocking exists on the TraceUnit',
      'Validate sample_id, sample_position, drawn_at and drawn_by',
      'Sign and submit tx_sampling against the crop cycle',
      'Register sample_id so a later LabReport resolves back to this crop cycle',
      'Leave the pipelinePointer unchanged and keep the stage open for repeat sampling',
    ],
  },
  {
    id: 'flow32',
    name: 'Farmed · Farmer records tx_harvest (HarvestEvent)',
    trigger: 'A farmer submits the Harvest form at stage_harvest',
    description: 'Emits tx_harvest and requires tx_stocking, closing the crop cycle into a harvest lot and its farm-gate sale. Advances the pointer to stage_farm_gate_receipt and hands off to dealer_trader declaring harvest_weight and count_grade.',
    steps: [
      'Confirm tx_stocking exists and no LotHold is active on the unit',
      'Validate harvest_lot, farming_method, harvest_date, harvest_weight (min 0), count_grade and agreed_rate (min 0)',
      'Sign and submit tx_harvest against the crop cycle',
      'Advance the pipelinePointer to stage_farm_gate_receipt',
      'Open a HandoffAgreement to dealer_trader declaring harvest_weight and count_grade',
      'Notify the dealer_trader incoming queue',
    ],
  },
  {
    id: 'flow33',
    name: 'Farmed · Dealer or trader records tx_ship_receive (ShipReceiveEvent)',
    trigger: 'A dealer_trader accepts the harvest handoff and submits the Custody transfer form at stage_farm_gate_receipt',
    description: 'Emits tx_ship_receive and requires tx_harvest, recording receipt at the farm gate and dispatch onward. Advances the pointer to stage_preprocessing and hands off to preprocessing_operator declaring quantity.',
    steps: [
      'Confirm tx_harvest exists and co-sign the incoming HandoffAgreement as ACCEPTED or flag a discrepancy',
      'Validate lot_ref, source_party, destination_party, quantity (min 0) and event_time',
      'Sign and submit tx_ship_receive against the unit',
      'Advance the pipelinePointer to stage_preprocessing',
      'Open a HandoffAgreement to preprocessing_operator declaring quantity',
      'Notify the preprocessing_operator incoming queue',
    ],
  },
  {
    id: 'flow34',
    name: 'Farmed · Pre-processing operator records tx_handling (HandlingEvent)',
    trigger: 'A preprocessing_operator accepts the dealer handoff and submits the Handling site event form at stage_preprocessing',
    description: 'Emits tx_handling and requires tx_ship_receive, recording the pre-processing site and the output lot it produces. Advances the pointer to stage_processing and hands off to plant_quality_manager declaring output_lot_ref.',
    steps: [
      'Confirm tx_ship_receive exists and co-sign the incoming HandoffAgreement',
      'Validate site_id, site_position, approval_number, controlling_party, in_audit_scope, operation, input_lot_ref and output_lot_ref',
      'Sign and submit tx_handling against the unit',
      'Record the parent-to-child link from input_lot_ref to output_lot_ref',
      'Advance the pipelinePointer to stage_processing and open a HandoffAgreement to plant_quality_manager declaring output_lot_ref',
      'Notify the plant_quality_manager incoming queue',
    ],
  },

  /* ───────── C. Stage flows · Wild Capture (TABLE 43) ───────── */
  {
    id: 'flow35',
    name: 'Wild · Skipper records tx_fishing (FishingTrip)',
    trigger: 'A skipper submits the Fishing trip form at stage_fishing',
    description: 'Emits tx_fishing, an origin_create transaction with no prerequisite, creating the TraceUnit whose origin unit is the FishingTrip. No handoff; the pointer moves into the on-vessel block that the skipper also owns.',
    steps: [
      'Validate trip_code, vessel_registration, fishing_licence, vessel_class, catch_lot, catch_area, trip_start, trip_end, capture_date, gear_type, species, weight (min 0) and position_source',
      'Check cert_vessel_registration and cert_fishing_licence are anchored against the trip, plus cert_letter_authorisation for high seas',
      'Sign the canonical payload with the skipper ed25519 key and submit tx_fishing',
      'Create the TraceUnit with its publicVerifyCode and currentStageKey stage_fishing',
      'Advance the pipelinePointer to stage_onvessel_processing and unlock stage_transhipment and stage_landing',
      'Notify the skipper that the trip is open on chain',
    ],
  },
  {
    id: 'flow36',
    name: 'Wild · Skipper records tx_onvessel_processing (OnvesselProcessingEvent)',
    trigger: 'A skipper submits the On-vessel processing form at stage_onvessel_processing',
    description: 'Emits tx_onvessel_processing and requires tx_fishing, recording the product form and weight after gutting or heading at sea. Repeatable with no handoff, so the pipeline pointer does not move.',
    steps: [
      'Confirm tx_fishing exists on the TraceUnit',
      'Validate lot_ref, product_form and processed_weight (min 0)',
      'Sign and submit tx_onvessel_processing against the fishing trip',
      'Append a StageTransition entry for the repeat occurrence',
      'Leave the pipelinePointer unchanged and keep the stage in the skipper work queue',
    ],
  },
  {
    id: 'flow37',
    name: 'Wild · Skipper records tx_transhipment (TranshipmentEvent)',
    trigger: 'A skipper submits the Transhipment form at stage_transhipment',
    description: 'Emits tx_transhipment and requires tx_fishing, recording the carrier vessel that took the catch at sea. Repeatable with no handoff.',
    steps: [
      'Confirm tx_fishing exists on the TraceUnit',
      'Validate lot_ref, carrier_vessel_name, carrier_vessel_id, carrier_flag, location, tranship_date and authorisation',
      'Sign and submit tx_transhipment against the fishing trip',
      'Pin the carrier flag and the transhipment authorisation to the chain-of-custody timeline',
      'Leave the pipelinePointer unchanged and keep the repeatable stage available',
    ],
  },
  {
    id: 'flow38',
    name: 'Wild · Skipper records tx_landing (LandingEvent)',
    trigger: 'A skipper submits the Landing form at stage_landing',
    description: 'Emits tx_landing and requires tx_fishing, recording the fishing harbour and the landed weight. Advances the pointer to stage_auction and hands off to auctioneer declaring landed_weight.',
    steps: [
      'Confirm tx_fishing exists on the TraceUnit',
      'Validate lot_ref, landing_location, landing_date, landing_authorisation and landed_weight (min 0)',
      'Sign and submit tx_landing against the fishing trip',
      'Advance the pipelinePointer to stage_auction',
      'Open a HandoffAgreement to auctioneer declaring landed_weight',
      'Notify the auctioneer incoming queue',
    ],
  },
  {
    id: 'flow39',
    name: 'Wild · Auctioneer records tx_auction (AuctionEvent)',
    trigger: 'An auctioneer accepts the landing handoff and submits the Auction and first sale form at stage_auction',
    description: 'Emits tx_auction, a merge-category transaction that requires tx_landing and combines contributing_lots into one merchant_lot. Advances the pointer to stage_assembly and hands off to assembler_supplier declaring weight.',
    steps: [
      'Confirm tx_landing exists and co-sign the incoming HandoffAgreement',
      'Validate merchant_lot, contributing_lots, buyer, weight (min 0) and sale_date',
      'Confirm every contributing catch lot exists on the unit history before merging',
      'Sign and submit tx_auction and record the merge from contributing_lots into merchant_lot',
      'Advance the pipelinePointer to stage_assembly and open a HandoffAgreement to assembler_supplier declaring weight',
      'Notify the assembler_supplier incoming queue',
    ],
  },
  {
    id: 'flow40',
    name: 'Wild · Assembler or supplier records tx_ship_receive (ShipReceiveEvent)',
    trigger: 'An assembler_supplier accepts the auction handoff and submits the Custody transfer form at stage_assembly',
    description: 'Emits tx_ship_receive and requires tx_auction, consolidating the merchant lot for onward movement. Advances the pointer to stage_wholesale and hands off to wholesaler declaring quantity.',
    steps: [
      'Confirm tx_auction exists and co-sign the incoming HandoffAgreement as ACCEPTED or flag a discrepancy',
      'Validate lot_ref, source_party, destination_party, quantity (min 0) and event_time',
      'Sign and submit tx_ship_receive against the unit',
      'Advance the pipelinePointer to stage_wholesale',
      'Open a HandoffAgreement to wholesaler declaring quantity',
      'Notify the wholesaler incoming queue',
    ],
  },
  {
    id: 'flow41',
    name: 'Wild · Wholesaler records tx_ship_receive (ShipReceiveEvent)',
    trigger: 'A wholesaler accepts the assembly handoff and submits the Custody transfer form at stage_wholesale',
    description: 'Emits tx_ship_receive and requires the assembly tx_ship_receive already on the unit, recording the wholesale holding leg. Advances the pointer to stage_cleaning and hands off to cleaning_operator declaring quantity.',
    steps: [
      'Confirm the assembly tx_ship_receive exists and co-sign the incoming HandoffAgreement',
      'Validate lot_ref, source_party, destination_party, quantity (min 0) and event_time',
      'Sign and submit tx_ship_receive against the unit',
      'Advance the pipelinePointer to stage_cleaning',
      'Open a HandoffAgreement to cleaning_operator declaring quantity',
      'Notify the cleaning_operator incoming queue',
    ],
  },
  {
    id: 'flow42',
    name: 'Wild · Cleaning operator records tx_handling (HandlingEvent)',
    trigger: 'A cleaning_operator accepts the wholesale handoff and submits the Handling site event form at stage_cleaning',
    description: 'Emits tx_handling and requires tx_ship_receive, recording the cleaning and pre-processing site and the output lot it produces. Advances the pointer to stage_processing and hands off to plant_quality_manager declaring output_lot_ref.',
    steps: [
      'Confirm tx_ship_receive exists and co-sign the incoming HandoffAgreement',
      'Validate site_id, site_position, approval_number, controlling_party, in_audit_scope, operation, input_lot_ref and output_lot_ref',
      'Sign and submit tx_handling against the unit',
      'Record the parent-to-child link from input_lot_ref to output_lot_ref',
      'Advance the pipelinePointer to stage_processing and open a HandoffAgreement to plant_quality_manager declaring output_lot_ref',
      'Notify the plant_quality_manager incoming queue',
    ],
  },

  /* ───────── C. Stage flows · shared tail, both profiles ───────── */
  {
    id: 'flow43',
    name: 'Shared · Plant quality manager records tx_processing (ProcessingBatch)',
    trigger: 'A plant_quality_manager accepts the incoming handoff and submits the Processing batch form at stage_processing',
    description: 'Runs on both profiles with no declared prerequisite transaction and no handoff, anchoring the ProcessingBatch that turns the received lot into a production batch. The pointer advances to stage_freezing_cold_storage.',
    steps: [
      'Co-sign the incoming HandoffAgreement from preprocessing_operator on farmed or cleaning_operator on wild',
      'Validate batch_number, input_lot_ref, species, product_form, raw_weight (min 0), finished_weight (min 0), yield_factor (0 to 1), production_date and human_welfare_policy',
      'Check cert_establishment and the FSSAI licence are anchored against the processing_plant',
      'Sign and submit tx_processing against the unit',
      'Advance the pipelinePointer to stage_freezing_cold_storage with no handoff',
      'Notify the plant quality team that the batch is open',
    ],
  },
  {
    id: 'flow44',
    name: 'Shared · Plant quality manager records tx_cold_storage (ProcessingBatch)',
    trigger: 'A plant_quality_manager submits the Processing batch form again at stage_freezing_cold_storage',
    description: 'Runs on both profiles, emits tx_cold_storage and requires tx_processing on the same ProcessingBatch. Advances the pointer to stage_export_documentation and hands off to exporter_administrator declaring finished_weight.',
    steps: [
      'Confirm tx_processing exists on the TraceUnit',
      'Validate the batch_number matches the processed batch and finished_weight (min 0) is final',
      'Confirm every LabReport on the batch has result_pass true and no LotHold is active',
      'Sign and submit tx_cold_storage against the unit',
      'Advance the pipelinePointer to stage_export_documentation and open a HandoffAgreement to exporter_administrator declaring finished_weight',
      'Notify the exporter_administrator incoming queue',
    ],
  },
  {
    id: 'flow45',
    name: 'Shared · Exporter administrator records tx_consignment (Consignment)',
    trigger: 'An exporter_administrator accepts the cold storage handoff and submits the Export consignment form at stage_export_documentation',
    description: 'Runs on both profiles, emits tx_consignment and requires tx_cold_storage, assembling the contained lots into one export consignment. Advances the pointer to stage_customs and hands off to customs_broker declaring total_weight.',
    steps: [
      'Confirm tx_cold_storage exists and co-sign the incoming HandoffAgreement',
      'Validate consignment_number, destination, buyer, input_lots, total_weight (min 0) and export_date',
      'Issue or anchor cert_health and cert_origin, plus cert_catch when destination is european_union on wild',
      'Sign and submit tx_consignment against the unit and refresh the ComplianceScorecard',
      'Advance the pipelinePointer to stage_customs and open a HandoffAgreement to customs_broker declaring total_weight',
      'Notify the customs_broker incoming queue',
    ],
  },
  {
    id: 'flow46',
    name: 'Shared · Customs broker records tx_customs (CustomsEvent)',
    trigger: 'A customs_broker accepts the export documentation handoff and submits the Customs clearance form at stage_customs',
    description: 'Runs on both profiles, emits tx_customs and requires tx_consignment, anchoring the shipping bill against the consignment. Advances the pointer to stage_shipping and hands off to transporter declaring shipping_bill_number.',
    steps: [
      'Confirm tx_consignment exists and co-sign the incoming HandoffAgreement',
      'Validate consignment_ref, shipping_bill_number, port_of_loading, customs_broker and cleared_date',
      'Check the mandatory certificates for the consignment are anchored before clearance is recorded',
      'Sign and submit tx_customs against the unit',
      'Advance the pipelinePointer to stage_shipping and open a HandoffAgreement to transporter declaring shipping_bill_number',
      'Notify the transporter incoming queue',
    ],
  },
  {
    id: 'flow47',
    name: 'Shared · Reefer logistics operator records tx_shipping (ShippingEvent)',
    trigger: 'A transporter accepts the customs handoff and submits the Ocean freight leg form at stage_shipping',
    description: 'Runs on both profiles, emits tx_shipping and requires tx_customs, anchoring the container, seal, bill of lading and reefer set point. Advances the pointer to stage_import and hands off to importer declaring container_number.',
    steps: [
      'Confirm tx_customs exists and co-sign the incoming HandoffAgreement',
      'Validate consignment_ref, container_number, seal_number, vessel_name, bill_of_lading, departure_port, arrival_port, sail_date and reefer_setpoint',
      'Sign and submit tx_shipping against the unit',
      'Record any accompanying TransportEvent leg so rule_transport_temperature can evaluate temperature_max',
      'Advance the pipelinePointer to stage_import and open a HandoffAgreement to importer declaring container_number',
      'Notify the importer incoming queue',
    ],
  },
  {
    id: 'flow48',
    name: 'Shared · Importer records tx_import (ImportEvent)',
    trigger: 'An importer accepts the shipping handoff and submits the Import clearance form at stage_import',
    description: 'Runs on both profiles, emits tx_import and requires tx_shipping, anchoring the border control post and import entry number. Advances the pointer to stage_distribution and hands off to distributor declaring import_entry_number.',
    steps: [
      'Confirm tx_shipping exists and co-sign the incoming HandoffAgreement as ACCEPTED or flag a discrepancy',
      'Validate consignment_ref, border_control_post, import_entry_number, importer_name and cleared_date',
      'Sign and submit tx_import against the unit',
      'Advance the pipelinePointer to stage_distribution',
      'Open a HandoffAgreement to distributor declaring import_entry_number',
      'Notify the distributor incoming queue',
    ],
  },
  {
    id: 'flow49',
    name: 'Shared · Distributor or repacker records tx_distribution (DistributionEvent)',
    trigger: 'A distributor accepts the import handoff and submits the Distribution form at stage_distribution',
    description: 'Runs on both profiles, emits tx_distribution and requires tx_import, linking the received lot to the repacked output lot. Advances the pointer to stage_retail and hands off to retailer declaring quantity.',
    steps: [
      'Confirm tx_import exists and co-sign the incoming HandoffAgreement',
      'Validate input_lot_ref, output_lot_ref, distributor_name, quantity (min 0) and relabel_date',
      'Sign and submit tx_distribution and record the parent-to-child lot link for the repack',
      'Advance the pipelinePointer to stage_retail',
      'Open a HandoffAgreement to retailer declaring quantity',
      'Notify the retailer incoming queue',
    ],
  },
  {
    id: 'flow50',
    name: 'Shared · Retailer records tx_retail (RetailEvent)',
    trigger: 'A retailer accepts the distribution handoff and submits the Retail delivery form at stage_retail',
    description: 'Runs on both profiles, emits tx_retail and requires tx_distribution, and is the terminal stage with no handoff. The pipeline closes and the publicVerifyCode QR becomes the consumer-facing end of the chain.',
    steps: [
      'Confirm tx_distribution exists and co-sign the incoming HandoffAgreement',
      'Validate input_lot_ref, retailer_name, destination_market, quantity (min 0) and sale_date',
      'Sign and submit tx_retail against the unit',
      'Close the pipeline by leaving the pipelinePointer at stage_retail with no outgoing handoff',
      'Finalise the ComplianceScorecard and publish the completed chain at /verify/:code',
    ],
  },

  /* ───────── D. Cross-cutting surface ───────── */
  {
    id: 'flow51',
    name: 'Forms · Enforce declared field constraints before signing',
    trigger: 'Any stage form or entity form is submitted',
    description: 'Beyond required and typed checks, the declared constraints in TABLE 74 are enforced before the payload is canonicalised and signed. A failure returns field-level errors and no ChainTransaction is created.',
    steps: [
      'Check text bounds such as organisation.legal_name minLen 2 and maxLen 200',
      'Check non-negative quantities such as processing_batch.raw_weight, harvest_event.harvest_weight, landing_event.landed_weight and ship_receive_event.quantity',
      'Check bounded numbers such as processing_batch.yield_factor between 0 and 1 and growout_reading.ph between 0 and 14',
      'Check enum and collection bindings resolve to a known value for fields such as catch_area, landing_location and substance',
      'Return field-level errors and abort before signing when any constraint fails',
    ],
  },
  {
    id: 'flow52',
    name: 'Records · List and detail with chain timeline and QR link',
    trigger: 'An authenticated user opens /records or /records/:id',
    description: 'The list shows every origin unit in the user scope with its live on-chain status, and the detail view renders one shipment chain-of-custody timeline with its lab results, certificates and disputes. Each record exposes its QR and public-verify link.',
    steps: [
      'Load the origin units, BroodstockEvent on farmed and FishingTrip on wild, filtered to the tenant and role scope',
      'Show each unit currentStageKey, handoffStatus and confirmed transaction count',
      'On detail, render every on-chain event in order with its ChainTransaction digest and finalised ChainBlock',
      'Attach LabReport results, anchored Certificate records and any open Dispute or LotHold',
      'Render the QR and the aquatrace.cerulea.io/verify/<code> link from TraceUnit.publicVerifyCode',
    ],
  },
];

module.exports = { FLOWS };
