'use strict';
let _c=6000;
const sid=()=>`s${String(++_c).padStart(5,'0')}`;
const f=(n,t,s,r,u,i,e)=>({id:sid(),name:n,type:t,storage:s,required:!!r,unique:!!u,indexed:!!i,encrypted:!!e});
const ADM={create:'admin',read:'admin',update:'admin',delete:'admin'};
const SYS={create:'admin',read:'auth',update:'admin',delete:'admin'};
const AUTH={create:'auth',read:'auth',update:'owner',delete:'admin'};
const e=(m,n,d,c,fs,a,o,p)=>({id:sid(),moduleId:m,name:n,description:d||undefined,isCore:!!c,fields:fs,access:a||AUTH,onChain:!!o,apiPublic:p!==undefined?!!p:true});

module.exports=[
  /* ── fees ── */
  e('fees','BaseFeeSnapshot','Base fee sampled at each block',1,[f('snapshotId','uuid','database',1,1,1),f('blockHeight','int','on-chain',1,1,1),f('baseFeeAGT','float','on-chain',1),f('targetGasUsed','int','on-chain'),f('actualGasUsed','int','on-chain'),f('adjustmentFactor','float','on-chain'),f('capturedAt','datetime','on-chain',1)],SYS,1,1),
  e('fees','GasUsageStat','Aggregated gas usage over a time period',0,[f('statId','uuid','database',1,1,1),f('period','string','database',1,0,1),f('totalGasUsed','int','database',1),f('avgGasPerTx','float','database'),f('peakGasBlock','int','database',0,0,1),f('highestFeeTx','bytes32','database'),f('computedAt','datetime','database',1)],SYS,0,1),
  e('fees','FeeAdjustmentEvent','EIP-1559 style fee adjustment record',0,[f('eventId','uuid','database',1,1,1),f('blockHeight','int','on-chain',1,0,1),f('previousFee','float','on-chain',1),f('newFee','float','on-chain',1),f('adjustmentReason','string','on-chain'),f('triggeredAt','datetime','on-chain',1),f('txHash','bytes32','on-chain')],SYS,1,1),
  e('fees','FeeDistributionEntry','Per-block distribution of collected fees',0,[f('entryId','uuid','database',1,1,1),f('blockHeight','int','on-chain',1,0,1),f('burnedAmount','float','on-chain',1),f('validatorTipAmount','float','on-chain',1),f('totalFeeCollected','float','on-chain',1),f('distributedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],SYS,1,1),
  e('fees','UserTransactionFee','Fee paid per user transaction',0,[f('feeId','uuid','database',1,1,1),f('txHash','bytes32','on-chain',1,1,1),f('senderAddress','address','on-chain',1,0,1),f('gasUsed','int','on-chain',1),f('gasPriceAGT','float','on-chain',1),f('totalFeeAGT','float','on-chain',1),f('blockHeight','int','on-chain',1,0,1)],AUTH,1,1),
  e('fees','FeeModelConfig','Active fee model parameters',1,[f('configId','uuid','database',1,1,1),f('baseFee','float','database',1),f('elasticityMultiplier','float','database',1),f('burnPercent','float','database',1),f('validatorTipPercent','float','database',1),f('effectiveFrom','datetime','database',1),f('updatedBy','address','database',1)],ADM,0,0),

  /* ── rpc ── */
  e('rpc','RPCEndpointConfig','RPC endpoint configuration',1,[f('endpointId','uuid','database',1,1,1),f('endpointType','string','database',1),f('url','string','database',1,1),f('authRequired','boolean','database',1),f('rateLimitPerMin','int','database',1),f('tlsEnabled','boolean','database',1),f('status','string','database',1,0,1)],ADM,0,0),
  e('rpc','RPCAccessKey','API key for RPC access',1,[f('keyId','uuid','database',1,1,1),f('ownerAddress','address','database',1,0,1),f('keyHash','string','database',1,1,0,1),f('scopes','json','database',1),f('createdAt','datetime','database',1),f('expiresAt','datetime','database'),f('isActive','boolean','database',1,0,1)],AUTH,0,0),
  e('rpc','RPCRequestLog','Log of every RPC method call',0,[f('logId','uuid','database',1,1,1),f('keyId','uuid','database',0,0,1),f('method','string','database',1,0,1),f('paramsHash','bytes32','database'),f('responseCode','int','database',1),f('durationMs','int','database'),f('requestedAt','datetime','database',1,0,1)],SYS,0,0),
  e('rpc','RPCMethodAllowlist','Allowed RPC methods per role',0,[f('entryId','uuid','database',1,1,1),f('method','string','database',1,1),f('requiredRole','string','database',1,0,1),f('requiresAuth','boolean','database',1),f('isEnabled','boolean','database',1),f('updatedBy','address','database',1),f('updatedAt','datetime','database',1)],ADM,0,0),
  e('rpc','RPCRateLimitRecord','Rate limit tracking per access key',0,[f('recordId','uuid','database',1,1,1),f('keyId','uuid','database',1,0,1),f('windowStart','datetime','database',1),f('requestCount','int','database',1),f('limitExceeded','boolean','database',1),f('penaltyUntil','datetime','database'),f('capturedAt','datetime','database',1)],SYS,0,0),
  e('rpc','RPCHealthSnapshot','Periodic health snapshot of the RPC endpoint',0,[f('snapshotId','uuid','database',1,1,1),f('endpointId','uuid','database',1,0,1),f('avgResponseMs','float','database'),f('errorRate','float','database'),f('uptimePercent','float','database',1),f('capturedAt','datetime','database',1,0,1),f('warningCount','int','database')],SYS,0,0),

  /* ── graphql-gateway ── */
  e('graphql-gateway','GraphQLClientApp','Registered application using the GraphQL API',1,[f('appId','uuid','database',1,1,1),f('appName','string','database',1),f('ownerAddress','address','database',1,0,1),f('apiKeyHash','string','database',1,1,0,1),f('allowedOperations','json','database'),f('createdAt','datetime','database',1),f('isActive','boolean','database',1,0,1)],ADM,0,0),
  e('graphql-gateway','GraphQLSchemaVersion','Deployed version of the GraphQL schema',0,[f('versionId','uuid','database',1,1,1),f('versionTag','string','database',1,1),f('schemaHash','bytes32','database',1),f('deployedAt','datetime','database',1),f('deployedBy','address','database',1),f('breakingChanges','boolean','database'),f('changelog','text','database')],ADM,0,0),
  e('graphql-gateway','GraphQLQueryLog','Log of every GraphQL query executed',0,[f('logId','uuid','database',1,1,1),f('appId','uuid','database',0,0,1),f('operationName','string','database',0,0,1),f('queryHash','bytes32','database',1),f('durationMs','int','database'),f('resultSize','int','database'),f('executedAt','datetime','database',1,0,1)],SYS,0,0),
  e('graphql-gateway','GraphQLDepthPolicy','Max query depth and complexity policy',0,[f('policyId','uuid','database',1,1,1),f('maxDepth','int','database',1),f('maxComplexity','int','database',1),f('enforceFrom','datetime','database',1),f('appliesTo','string','database',1),f('updatedBy','address','database',1),f('notes','text','database')],ADM,0,0),
  e('graphql-gateway','GraphQLRateLimitRecord','Rate limit tracking per GraphQL client',0,[f('recordId','uuid','database',1,1,1),f('appId','uuid','database',1,0,1),f('windowStart','datetime','database',1),f('queryCount','int','database',1),f('limitExceeded','boolean','database',1),f('resetAt','datetime','database'),f('penaltyLevel','string','database')],SYS,0,0),
  e('graphql-gateway','GraphQLIntrospectionPolicy','Policy controlling schema introspection access',0,[f('policyId','uuid','database',1,1,1),f('introspectionEnabled','boolean','database',1),f('allowedRoles','json','database',1),f('restrictedFields','json','database'),f('enforceFrom','datetime','database',1),f('updatedBy','address','database',1),f('notes','text','database')],ADM,0,0),

  /* ── ws-subscriptions ── */
  e('ws-subscriptions','WebSocketSession','Active WebSocket client session',1,[f('sessionId','uuid','database',1,1,1),f('clientAddress','address','database',1,0,1),f('connectedAt','datetime','database',1),f('lastPingAt','datetime','database'),f('activeSubscriptions','int','database'),f('agentType','string','database',1),f('disconnectedAt','datetime','database')],AUTH,0,1),
  e('ws-subscriptions','SubscriptionFilter','Filter definition for a WebSocket subscription',0,[f('filterId','uuid','database',1,1,1),f('sessionId','uuid','database',1,0,1),f('eventType','string','database',1,0,1),f('filterCriteria','json','database'),f('createdAt','datetime','database',1),f('isActive','boolean','database',1),f('priority','int','database')],AUTH,0,0),
  e('ws-subscriptions','EventDeliveryRecord','Record of a delivered subscription event',0,[f('deliveryId','uuid','database',1,1,1),f('sessionId','uuid','database',1,0,1),f('eventType','string','database',1,0,1),f('eventId','uuid','database',1),f('deliveredAt','datetime','database',1),f('payloadHash','bytes32','database'),f('acknowledged','boolean','database')],SYS,0,0),
  e('ws-subscriptions','WebSocketHeartbeat','Ping/pong heartbeat record per session',0,[f('heartbeatId','uuid','database',1,1,1),f('sessionId','uuid','database',1,0,1),f('pingAt','datetime','database',1),f('pongAt','datetime','database'),f('latencyMs','int','database'),f('connectionStatus','string','database',1)],SYS,0,0),
  e('ws-subscriptions','SubscriptionRateLimit','Rate limit tracking per WebSocket session',0,[f('limitId','uuid','database',1,1,1),f('sessionId','uuid','database',1,0,1),f('windowStart','datetime','database',1),f('eventCount','int','database',1),f('limitExceeded','boolean','database',1),f('resetAt','datetime','database'),f('penaltyApplied','boolean','database')],SYS,0,0),
  e('ws-subscriptions','WebSocketErrorLog','Error log for WebSocket connection issues',0,[f('errorId','uuid','database',1,1,1),f('sessionId','uuid','database',0,0,1),f('errorCode','string','database',1,0,1),f('errorMessage','text','database',1),f('occurredAt','datetime','database',1),f('connectionDropped','boolean','database',1),f('retryAttempted','boolean','database')],SYS,0,0),

  /* ── api-gateway ── */
  e('api-gateway','APIKeyRecord','API key for accessing the gateway',1,[f('keyId','uuid','database',1,1,1),f('ownerAddress','address','database',1,0,1),f('keyPrefix','string','database',1),f('keyHash','string','database',1,1,0,1),f('scopes','json','database',1),f('createdAt','datetime','database',1),f('expiresAt','datetime','database',0,0,1)],AUTH,0,0),
  e('api-gateway','GatewayRouteConfig','Route configuration in the API gateway',0,[f('routeId','uuid','database',1,1,1),f('pathPattern','string','database',1,1),f('targetService','string','database',1),f('authRequired','boolean','database',1),f('rateLimitPerMin','int','database'),f('corsEnabled','boolean','database'),f('isActive','boolean','database',1)],ADM,0,0),
  e('api-gateway','APIRequestLog','Log of every inbound API request',0,[f('logId','uuid','database',1,1,1),f('keyId','uuid','database',0,0,1),f('route','string','database',1,0,1),f('method','string','database',1),f('statusCode','int','database',1,0,1),f('durationMs','int','database'),f('requestedAt','datetime','database',1,0,1)],SYS,0,0),
  e('api-gateway','CORSPolicy','Cross-origin resource sharing policy',0,[f('policyId','uuid','database',1,1,1),f('allowedOrigins','json','database',1),f('allowedHeaders','json','database',1),f('maxAgeSeconds','int','database'),f('enforceFrom','datetime','database',1),f('updatedBy','address','database',1),f('notes','text','database')],ADM,0,0),
  e('api-gateway','GatewayRateLimitRule','Rate limiting rule per key or route',0,[f('ruleId','uuid','database',1,1,1),f('appliesTo','string','database',1,0,1),f('limitPerMinute','int','database',1),f('limitPerHour','int','database'),f('penaltyDurationMins','int','database'),f('isActive','boolean','database',1),f('updatedAt','datetime','database',1)],ADM,0,0),
  e('api-gateway','GatewayAuditEntry','Audit entry for gateway config changes',0,[f('auditId','uuid','database',1,1,1),f('keyId','uuid','database',0,0,1),f('action','string','database',1),f('resourcePath','string','database',1),f('ipAddress','string','database',1,0,0,1),f('outcome','string','database',1),f('auditedAt','datetime','database',1,0,1)],ADM,0,0),

  /* ── metrics-dashboards ── */
  e('metrics-dashboards','MetricSeries','Time-series metric data',1,[f('seriesId','uuid','database',1,1,1),f('metricName','string','database',1,0,1),f('labels','json','database'),f('dataPoints','json','database',1),f('resolution','string','database',1),f('capturedFrom','datetime','database',1),f('capturedUntil','datetime','database',1)],SYS,0,0),
  e('metrics-dashboards','AlertRule','Rule that triggers an alert on threshold breach',1,[f('ruleId','uuid','database',1,1,1),f('metricName','string','database',1,0,1),f('condition','string','database',1),f('threshold','float','database',1),f('severity','string','database',1,0,1),f('notifyChannels','json','database',1),f('isActive','boolean','database',1)],ADM,0,0),
  e('metrics-dashboards','AlertFiringEvent','Record of a fired alert',0,[f('eventId','uuid','database',1,1,1),f('ruleId','uuid','database',1,0,1),f('firedAt','datetime','database',1,0,1),f('resolvedAt','datetime','database'),f('peakValue','float','database',1),f('affectedService','string','database',1),f('notifiedCount','int','database')],SYS,0,0),
  e('metrics-dashboards','DashboardConfig','Saved dashboard layout configuration',0,[f('dashboardId','uuid','database',1,1,1),f('dashboardName','string','database',1,1),f('ownerRole','string','database',1),f('panelLayout','json','database',1),f('refreshIntervalSecs','int','database'),f('createdAt','datetime','database',1),f('isPublic','boolean','database')],ADM,0,0),
  e('metrics-dashboards','MonitoredService','Service registered for health monitoring',0,[f('serviceId','uuid','database',1,1,1),f('serviceName','string','database',1,1),f('endpoint','string','database',1),f('checkIntervalSecs','int','database',1),f('lastCheckAt','datetime','database',0,0,1),f('uptimePct','float','database'),f('alertsEnabled','boolean','database',1)],ADM,0,0),
  e('metrics-dashboards','MetricAggregationJob','Scheduled job that computes aggregate metrics',0,[f('jobId','uuid','database',1,1,1),f('aggregationType','string','database',1),f('sourceMetrics','json','database',1),f('outputMetric','string','database',1),f('schedule','string','database',1),f('lastRunAt','datetime','database',0,0,1),f('status','string','database',1,0,1)],ADM,0,0),

  /* ── log-shipping ── */
  e('log-shipping','LogShipmentBatch','Batch of logs shipped to the destination',0,[f('batchId','uuid','database',1,1,1),f('sourceService','string','database',1,0,1),f('logCount','int','database',1),f('startTimestamp','datetime','database',1),f('endTimestamp','datetime','database',1),f('shippedAt','datetime','database',1,0,1),f('destination','string','database',1)],SYS,0,0),
  e('log-shipping','LogRetentionPolicy','Retention policy per log type',1,[f('policyId','uuid','database',1,1,1),f('logType','string','database',1,1),f('retentionDays','int','database',1),f('archiveEnabled','boolean','database',1),f('archiveDestination','string','database'),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),
  e('log-shipping','LogAnomalyFlag','Anomalous pattern detected in a log batch',0,[f('flagId','uuid','database',1,1,1),f('batchId','uuid','database',1,0,1),f('anomalyType','string','database',1,0,1),f('severity','string','database',1),f('description','text','database',1),f('detectedAt','datetime','database',1),f('reviewedBy','address','database')],SYS,0,0),
  e('log-shipping','LogShippingDestination','Configured destination for log shipments',1,[f('destinationId','uuid','database',1,1,1),f('destinationName','string','database',1,1),f('endpoint','string','database',1),f('authType','string','database',1),f('encryptionEnabled','boolean','database',1),f('isActive','boolean','database',1),f('lastSyncAt','datetime','database',0,0,1)],ADM,0,0),
  e('log-shipping','LogIndexEntry','Search index entry for a log record',0,[f('indexId','uuid','database',1,1,1),f('logTimestamp','datetime','database',1,0,1),f('sourceService','string','database',1,0,1),f('level','string','database',1,0,1),f('messageHash','bytes32','database',1),f('batchId','uuid','database',1,0,1),f('indexedAt','datetime','database',1)],SYS,0,0),
  e('log-shipping','LogShippingError','Error encountered during log shipment',0,[f('errorId','uuid','database',1,1,1),f('batchId','uuid','database',1,0,1),f('errorCode','string','database',1),f('errorMessage','text','database',1),f('retryCount','int','database'),f('resolvedAt','datetime','database'),f('failedAt','datetime','database',1)],SYS,0,0),

  /* ── backups-restore ── */
  e('backups-restore','BackupSnapshot','Chain state snapshot for recovery',1,[f('snapshotId','uuid','database',1,1,1),f('snapshotType','string','database',1,0,1),f('blockHeight','int','database',1,0,1),f('snapshotAt','datetime','database',1),f('storageKey','string','database',1),f('sizeBytes','int','database'),f('checksumHash','bytes32','database',1)],ADM,0,0),
  e('backups-restore','BackupStorageLocation','Configured storage for backup files',1,[f('locationId','uuid','database',1,1,1),f('provider','string','database',1),f('bucket','string','database',1),f('region','string','database',1),f('encryptionKeyId','string','database',1),f('isActive','boolean','database',1),f('lastVerifiedAt','datetime','database')],ADM,0,0),
  e('backups-restore','RestoreJob','A restore operation from a backup snapshot',0,[f('jobId','uuid','database',1,1,1),f('snapshotId','uuid','database',1,0,1),f('targetBlockHeight','int','database'),f('requestedBy','address','database',1),f('startedAt','datetime','database',1),f('completedAt','datetime','database'),f('status','string','database',1,0,1)],ADM,0,0),
  e('backups-restore','BackupIntegrityCheck','Verification run on a backup snapshot',0,[f('checkId','uuid','database',1,1,1),f('snapshotId','uuid','database',1,0,1),f('checkedAt','datetime','database',1),f('checksumValid','boolean','database',1),f('errorDetails','text','database'),f('verifiedBy','address','database',1),f('status','string','database',1)],ADM,0,0),
  e('backups-restore','BackupScheduleConfig','Schedule configuration for automated backups',1,[f('scheduleId','uuid','database',1,1,1),f('backupType','string','database',1),f('cronExpression','string','database',1),f('retentionCount','int','database',1),f('destinationId','uuid','database',1),f('isEnabled','boolean','database',1),f('updatedBy','address','database',1)],ADM,0,0),
  e('backups-restore','PointInTimeRecovery','Point-in-time recovery request',0,[f('recoveryId','uuid','database',1,1,1),f('targetTimestamp','datetime','database',1),f('snapshotId','uuid','database',1,0,1),f('requestedBy','address','database',1),f('estimatedDurationMins','int','database'),f('status','string','database',1,0,1),f('completedAt','datetime','database')],ADM,0,0),
];
