'use strict';
let _c=7000;
const sid=()=>`s${String(++_c).padStart(5,'0')}`;
const f=(n,t,s,r,u,i,e)=>({id:sid(),name:n,type:t,storage:s,required:!!r,unique:!!u,indexed:!!i,encrypted:!!e});
const ADM={create:'admin',read:'admin',update:'admin',delete:'admin'};
const SYS={create:'admin',read:'auth',update:'admin',delete:'admin'};
const AUTH={create:'auth',read:'auth',update:'owner',delete:'admin'};
const OWN={create:'owner',read:'owner',update:'owner',delete:'admin'};
const PUB={create:'auth',read:'public',update:'owner',delete:'admin'};
const e=(m,n,d,c,fs,a,o,p)=>({id:sid(),moduleId:m,name:n,description:d||undefined,isCore:!!c,fields:fs,access:a||AUTH,onChain:!!o,apiPublic:p!==undefined?!!p:true});

module.exports=[
  /* ── wallet-auth ── */
  e('wallet-auth','WalletSession','Active authenticated session for a wallet',1,[f('sessionId','uuid','database',1,1,1),f('walletAddress','address','database',1,0,1),f('sessionToken','string','database',1,1,0,1),f('createdAt','datetime','database',1),f('expiresAt','datetime','database',1,0,1),f('lastActivityAt','datetime','database'),f('ipAddress','string','database',0,0,0,1)],OWN,0,0),
  e('wallet-auth','AuthNonce','One-time nonce issued for wallet sign-in',0,[f('nonceId','uuid','database',1,1,1),f('walletAddress','address','database',1,0,1),f('nonce','string','database',1,1),f('issuedAt','datetime','database',1),f('usedAt','datetime','database'),f('expiresAt','datetime','database',1,0,1),f('purpose','string','database',1)],SYS,0,0),
  e('wallet-auth','WalletAllowlistEntry','Wallet approved to access the platform',1,[f('entryId','uuid','database',1,1,1),f('walletAddress','address','on-chain',1,1,1),f('actorType','string','on-chain',1,0,1),f('addedBy','address','database',1),f('addedAt','datetime','on-chain',1),f('expiresAt','datetime','database'),f('notes','text','database')],ADM,1,0),
  e('wallet-auth','SignatureChallenge','Challenge payload for wallet sign-in',0,[f('challengeId','uuid','database',1,1,1),f('walletAddress','address','database',1,0,1),f('challenge','string','database',1,1),f('issuedAt','datetime','database',1),f('expiresAt','datetime','database',1,0,1),f('verified','boolean','database',1),f('verifiedAt','datetime','database')],SYS,0,0),
  e('wallet-auth','AuthAttemptLog','Log of every authentication attempt',0,[f('logId','uuid','database',1,1,1),f('walletAddress','address','database',1,0,1),f('attemptType','string','database',1),f('success','boolean','database',1,0,1),f('failureReason','string','database'),f('attemptedAt','datetime','database',1,0,1),f('ipAddress','string','database',0,0,0,1)],SYS,0,0),
  e('wallet-auth','SessionRevocationRecord','Record of a manually revoked session',0,[f('revocationId','uuid','database',1,1,1),f('sessionId','uuid','database',1,0,1),f('walletAddress','address','on-chain',1,0,1),f('revokedBy','address','database',1),f('revokedAt','datetime','on-chain',1),f('reason','string','database',1),f('txHash','bytes32','on-chain')],ADM,1,0),

  /* ── session-keys ── */
  e('session-keys','SessionKeyRecord','Short-lived session key for dApp interactions',1,[f('keyId','uuid','database',1,1,1),f('ownerAddress','address','database',1,0,1),f('keyHash','string','database',1,1,0,1),f('scopes','json','database',1),f('ttlMins','int','database',1),f('createdAt','datetime','database',1),f('expiresAt','datetime','database',1,0,1)],OWN,0,0),
  e('session-keys','SessionKeyScope','Individual permission scope bound to a key',0,[f('scopeId','uuid','database',1,1,1),f('keyId','uuid','database',1,0,1),f('permittedActions','json','database',1),f('resourcePattern','string','database',1),f('createdAt','datetime','database',1),f('isActive','boolean','database',1),f('grantedBy','address','database')],OWN,0,0),
  e('session-keys','KeyRotationEvent','Session key rotation record',0,[f('rotationId','uuid','database',1,1,1),f('oldKeyId','uuid','database',1,0,1),f('newKeyId','uuid','database',1,0,1),f('rotatedAt','datetime','database',1),f('rotationReason','string','database'),f('initiatedBy','address','database',1),f('ipAddress','string','database',0,0,0,1)],OWN,0,0),
  e('session-keys','KeyUsageLog','Log of actions performed with a session key',0,[f('logId','uuid','database',1,1,1),f('keyId','uuid','database',1,0,1),f('action','string','database',1,0,1),f('resourceId','uuid','database'),f('usedAt','datetime','database',1,0,1),f('success','boolean','database',1),f('ipAddress','string','database',0,0,0,1)],SYS,0,0),
  e('session-keys','SessionKeyExpiry','Notification record for an expired session key',0,[f('expiryId','uuid','database',1,1,1),f('keyId','uuid','database',1,1,1),f('expiredAt','datetime','database',1),f('autoRevoked','boolean','database',1),f('lastUsedAt','datetime','database'),f('notificationSent','boolean','database')],SYS,0,0),
  e('session-keys','DeviceSessionBinding','Binding of a session key to a device',0,[f('bindingId','uuid','database',1,1,1),f('keyId','uuid','database',1,0,1),f('deviceEUI','string','database',1,0,1),f('boundAt','datetime','database',1),f('deviceType','string','database',1),f('isActive','boolean','database',1),f('unboundAt','datetime','database')],OWN,0,0),

  /* ── rbac ── */
  e('rbac','RoleDefinition','Named role with its permission set',1,[f('roleId','uuid','database',1,1,1),f('roleName','string','database',1,1),f('description','text','database'),f('permissions','json','database',1),f('inheritFrom','uuid','database'),f('createdAt','datetime','database',1),f('isActive','boolean','database',1,0,1)],ADM,0,0),
  e('rbac','RoleAssignment','Role granted to an actor',1,[f('assignmentId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('roleId','uuid','database',1,0,1),f('assignedBy','address','database',1),f('assignedAt','datetime','database',1),f('expiresAt','datetime','database'),f('scope','string','database')],ADM,0,0),
  e('rbac','PermissionPolicy','Policy document describing resource access rules',1,[f('policyId','uuid','database',1,1,1),f('policyName','string','database',1,1),f('resource','string','database',1,0,1),f('actions','json','database',1),f('conditions','json','database'),f('createdAt','datetime','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),
  e('rbac','PolicyVersion','Versioned snapshot of a permission policy',0,[f('versionId','uuid','database',1,1,1),f('policyId','uuid','database',1,0,1),f('versionNumber','int','database',1),f('changes','json','database',1),f('publishedBy','address','database',1),f('publishedAt','datetime','database',1),f('isActive','boolean','database',1,0,1)],ADM,0,0),
  e('rbac','RoleAuditEntry','Audit log of role assignment changes',0,[f('auditId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('changeType','string','database',1),f('oldRoleId','uuid','database'),f('newRoleId','uuid','database'),f('changedBy','address','database',1),f('changedAt','datetime','database',1,0,1)],ADM,0,0),
  e('rbac','ResourcePermission','Explicit permission entry per role and resource type',0,[f('permId','uuid','database',1,1,1),f('roleId','uuid','database',1,0,1),f('resourceType','string','database',1,0,1),f('allowedActions','json','database',1),f('denyActions','json','database'),f('priority','int','database'),f('isActive','boolean','database',1)],ADM,0,0),

  /* ── org-accounts ── */
  e('org-accounts','OrgInvitation','Invitation to join an organization',0,[f('inviteId','uuid','database',1,1,1),f('orgId','uuid','database',1,0,1),f('invitedEmail','string','database',1,0,0,1),f('invitedRole','string','database',1),f('invitedBy','address','database',1),f('invitedAt','datetime','database',1),f('expiresAt','datetime','database',1,0,1)],AUTH,0,0),
  e('org-accounts','OrgMembership','Active membership of an actor in an org',1,[f('membershipId','uuid','database',1,1,1),f('orgId','uuid','database',1,0,1),f('actorId','uuid','database',1,0,1),f('role','string','database',1,0,1),f('joinedAt','datetime','database',1),f('status','string','database',1,0,1),f('inviteId','uuid','database')],ADM,0,0),
  e('org-accounts','OrgBillingRecord','Billing record for an organization',0,[f('billingId','uuid','database',1,1,1),f('orgId','uuid','database',1,0,1),f('billingPeriod','string','database',1),f('amountINR','float','database',1),f('paymentStatus','string','database',1,0,1),f('invoiceId','uuid','database'),f('paidAt','datetime','database')],ADM,0,0),
  e('org-accounts','OrgApiKeyAssignment','API key assigned to an organization',0,[f('assignmentId','uuid','database',1,1,1),f('orgId','uuid','database',1,0,1),f('keyId','uuid','database',1,0,1),f('assignedBy','address','database',1),f('assignedAt','datetime','database',1),f('purpose','string','database'),f('isActive','boolean','database',1)],ADM,0,0),
  e('org-accounts','OrgActivityEntry','Activity log for an organization',0,[f('activityId','uuid','database',1,1,1),f('orgId','uuid','database',1,0,1),f('actorId','uuid','database',1,0,1),f('actionType','string','database',1,0,1),f('resourceId','uuid','database'),f('description','text','database',1),f('occurredAt','datetime','database',1,0,1)],AUTH,0,0),
  e('org-accounts','OrgSettingsConfig','Configuration settings for an organization',0,[f('configId','uuid','database',1,1,1),f('orgId','uuid','database',1,1,1),f('maxMembers','int','database',1),f('allowExternalActors','boolean','database'),f('mfaRequired','boolean','database'),f('updatedBy','address','database',1),f('updatedAt','datetime','database',1)],ADM,0,0),

  /* ── kyc ── */
  e('kyc','KYCSubmission','KYC application submitted by an actor',1,[f('submissionId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('submittedAt','datetime','database',1),f('submittedDocCount','int','database'),f('provider','string','database',1),f('status','string','database',1,0,1),f('expiresAt','datetime','database')],AUTH,0,0),
  e('kyc','KYCDocument','Supporting document in a KYC submission',0,[f('docId','uuid','database',1,1,1),f('submissionId','uuid','database',1,0,1),f('documentType','string','database',1,0,1),f('documentNumber','string','database',0,0,0,1),f('issuingAuthority','string','database',1),f('docHash','bytes32','database',1),f('uploadedAt','datetime','database',1)],AUTH,0,0),
  e('kyc','KYCVerificationResult','Outcome of a KYC review',1,[f('resultId','uuid','database',1,1,1),f('submissionId','uuid','database',1,1,1),f('verifiedAt','datetime','database',1),f('verifiedBy','string','database',1),f('outcome','string','database',1,0,1),f('confidenceScore','float','database'),f('notes','text','database')],ADM,0,0),
  e('kyc','KYCRejectionRecord','Record of a failed KYC check',0,[f('rejectionId','uuid','database',1,1,1),f('submissionId','uuid','database',1,0,1),f('rejectedAt','datetime','database',1),f('rejectionCode','string','database',1),f('rejectionReason','text','database',1),f('canReapply','boolean','database',1),f('reapplyAfter','datetime','database')],ADM,0,0),
  e('kyc','KYCRecheckSchedule','Scheduled periodic re-verification',0,[f('scheduleId','uuid','database',1,1,1),f('actorId','uuid','database',1,1,1),f('nextRecheckAt','datetime','database',1,0,1),f('recheckReason','string','database'),f('lastVerifiedAt','datetime','database'),f('automaticRecheck','boolean','database',1),f('reminderSentAt','datetime','database')],ADM,0,0),
  e('kyc','KYCWebhookEvent','Webhook payload from KYC provider',0,[f('eventId','uuid','database',1,1,1),f('provider','string','database',1,0,1),f('eventType','string','database',1,0,1),f('actorId','uuid','database',0,0,1),f('eventPayloadHash','bytes32','database',1),f('receivedAt','datetime','database',1),f('processed','boolean','database',1)],SYS,0,0),

  /* ── device-trust ── */
  e('device-trust','TrustedDevice','Device registered and trusted for platform use',1,[f('deviceId','uuid','database',1,1,1),f('ownerAddress','address','database',1,0,1),f('deviceFingerprint','string','database',1,1,0,1),f('deviceType','string','database',1,0,1),f('registeredAt','datetime','database',1),f('lastVerifiedAt','datetime','database'),f('isActive','boolean','database',1,0,1)],AUTH,0,0),
  e('device-trust','DeviceAuthChallenge','Challenge issued to a device for authentication',0,[f('challengeId','uuid','database',1,1,1),f('deviceId','uuid','database',1,0,1),f('challenge','string','database',1,1),f('issuedAt','datetime','database',1),f('expiresAt','datetime','database',1,0,1),f('solved','boolean','database',1),f('solvedAt','datetime','database')],SYS,0,0),
  e('device-trust','DeviceBindingRecord','Binding of a device to a specific actor',0,[f('bindingId','uuid','database',1,1,1),f('deviceId','uuid','database',1,0,1),f('actorId','uuid','database',1,0,1),f('boundAt','datetime','database',1),f('boundPurpose','string','database',1),f('isActive','boolean','database',1),f('unboundAt','datetime','database')],AUTH,0,0),
  e('device-trust','DeviceRiskScore','Risk score assessed for a device',0,[f('scoreId','uuid','database',1,1,1),f('deviceId','uuid','database',1,1,1),f('riskScore','float','database',1),f('riskFactors','json','database',1),f('computedAt','datetime','database',1,0,1),f('recommendation','string','database'),f('lastUpdatedAt','datetime','database',1)],SYS,0,0),
  e('device-trust','DeviceTrustPolicy','Policy defining device trust requirements',0,[f('policyId','uuid','database',1,1,1),f('deviceType','string','database',1,1),f('minFirmwareVersion','string','database'),f('requireCalibration','boolean','database'),f('maxRiskScore','float','database',1),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),
  e('device-trust','DeviceSuspensionEvent','Device suspended from the platform',0,[f('eventId','uuid','database',1,1,1),f('deviceId','uuid','database',1,0,1),f('suspendedBy','address','database',1),f('suspensionReason','string','database',1),f('suspendedAt','datetime','database',1),f('resolvedAt','datetime','database'),f('txHash','bytes32','on-chain')],ADM,1,0),

  /* ── gasless-relayer ── */
  e('gasless-relayer','RelayerRequest','Request to relay a sponsored transaction',1,[f('requestId','uuid','database',1,1,1),f('senderAddress','address','database',1,0,1),f('targetContract','address','database',1),f('encodedTxHash','bytes32','database',1),f('requestedAt','datetime','database',1),f('status','string','database',1,0,1),f('sponsorAddress','address','database',1)],AUTH,0,0),
  e('gasless-relayer','SponsorshipAllowance','Daily gas sponsorship allowance per actor',1,[f('allowanceId','uuid','database',1,1,1),f('actorId','uuid','database',1,1,1),f('actorRole','string','database',1,0,1),f('dailyTxLimit','int','database',1),f('usedToday','int','database'),f('resetAt','datetime','database',1),f('isActive','boolean','database',1)],AUTH,0,0),
  e('gasless-relayer','RelayerTransaction','On-chain relay transaction record',0,[f('txId','uuid','database',1,1,1),f('requestId','uuid','database',1,1,1),f('txHash','bytes32','on-chain',1,1,1),f('gasUsed','int','on-chain',1),f('sponsoredAGT','float','on-chain',1),f('submittedAt','datetime','database',1),f('confirmedAt','datetime','on-chain')],SYS,1,0),
  e('gasless-relayer','SponsorshipExhaustionEvent','Event when a daily quota is exhausted',0,[f('eventId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('exhaustedAt','datetime','database',1),f('requestsToday','int','database',1),f('dailyLimit','int','database',1),f('alertSent','boolean','database'),f('resetAt','datetime','database',1)],SYS,0,0),
  e('gasless-relayer','RelayerPolicyConfig','Policy defining sponsorship rules',1,[f('configId','uuid','database',1,1,1),f('sponsoredRoles','json','database',1),f('maxGasPerTx','int','database',1),f('dailyCap','json','database',1),f('fundingAccount','address','database',1),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),
  e('gasless-relayer','SponsoredBalanceRecord','Snapshot of the relayer funding balance',0,[f('balanceId','uuid','database',1,1,1),f('fundingAccount','address','on-chain',1,0,1),f('balanceAGT','float','on-chain',1),f('asOfBlock','int','on-chain',1),f('replenishedAt','datetime','database'),f('lowBalanceAlert','boolean','database'),f('capturedAt','datetime','database',1)],ADM,1,0),

  /* ── did-vc-ledger ── */
  e('did-vc-ledger','DIDDocument','Decentralised Identity document anchored on-chain',1,[f('did','string','on-chain',1,1,1),f('controllerAddress','address','on-chain',1,0,1),f('verificationMethods','json','on-chain',1),f('serviceEndpoints','json','database'),f('createdAt','datetime','on-chain',1),f('updatedAt','datetime','database'),f('deactivated','boolean','on-chain')],AUTH,1,1),
  e('did-vc-ledger','VerifiableCredential','On-chain verifiable credential issued to an actor',1,[f('vcId','uuid','on-chain',1,1,1),f('issuerDID','string','on-chain',1,0,1),f('holderDID','string','on-chain',1,0,1),f('credentialType','string','on-chain',1,0,1),f('claims','json','database',1),f('issuedAt','datetime','on-chain',1),f('expiresAt','datetime','on-chain')],AUTH,1,1),
  e('did-vc-ledger','CredentialRevocation','On-chain revocation of a VC',0,[f('revocationId','uuid','on-chain',1,1,1),f('vcId','uuid','on-chain',1,0,1),f('revokedBy','address','on-chain',1),f('revokedAt','datetime','on-chain',1),f('reason','string','database',1),f('revocationListHash','bytes32','on-chain'),f('txHash','bytes32','on-chain',1)],ADM,1,0),
  e('did-vc-ledger','DIDResolutionRecord','Log of DID resolution requests',0,[f('resolutionId','uuid','database',1,1,1),f('did','string','database',1,0,1),f('resolvedAt','datetime','database',1),f('resolutionStatus','string','database',1),f('documentHash','bytes32','database'),f('resolverVersion','string','database')],SYS,0,0),
  e('did-vc-ledger','VCSchemaEntry','Schema definition for a credential type',0,[f('schemaId','uuid','database',1,1,1),f('schemaName','string','database',1,1),f('schemaVersion','string','database',1),f('jsonSchema','json','database',1),f('publishedBy','address','database',1),f('publishedAt','datetime','database',1),f('isActive','boolean','database',1)],ADM,0,0),
  e('did-vc-ledger','CredentialPresentationLog','Log when an actor presents a credential',0,[f('presentationId','uuid','database',1,1,1),f('holderDID','string','database',1,0,1),f('vcIds','json','database',1),f('presentedTo','string','database',1),f('presentedAt','datetime','database',1),f('verifiedAt','datetime','database'),f('outcome','string','database',1)],AUTH,0,0),

  /* ── aml-screening ── */
  e('aml-screening','ScreeningRequest','AML screening request for a wallet',1,[f('requestId','uuid','database',1,1,1),f('walletAddress','address','database',1,0,1),f('actorId','uuid','database',0,0,1),f('requestedAt','datetime','database',1),f('provider','string','database',1),f('requestHash','bytes32','database',1),f('status','string','database',1,0,1)],ADM,0,0),
  e('aml-screening','ScreeningResult','Result returned from the AML provider',1,[f('resultId','uuid','database',1,1,1),f('requestId','uuid','database',1,1,1),f('riskLevel','string','database',1,0,1),f('riskScore','float','database',1),f('matchedFlags','json','database'),f('screenedAt','datetime','database',1),f('nextRecheckAt','datetime','database')],ADM,0,0),
  e('aml-screening','WatchlistMatchRecord','Record of a watchlist hit',0,[f('matchId','uuid','database',1,1,1),f('requestId','uuid','database',1,0,1),f('matchedList','string','database',1),f('matchedEntry','string','database',1,0,0,1),f('confidence','float','database',1),f('flaggedAt','datetime','database',1),f('reviewedBy','address','database')],ADM,0,0),
  e('aml-screening','RiskProfile','Ongoing risk profile for a wallet',0,[f('profileId','uuid','database',1,1,1),f('walletAddress','address','database',1,1,1),f('currentRiskLevel','string','database',1,0,1),f('lastScreenedAt','datetime','database',1),f('screeningCount','int','database'),f('autoRecheckAt','datetime','database',0,0,1),f('flagged','boolean','database',1)],ADM,0,0),
  e('aml-screening','ScreeningAlertRecord','Alert triggered by a screening result',0,[f('alertId','uuid','database',1,1,1),f('requestId','uuid','database',1,0,1),f('alertType','string','database',1,0,1),f('severity','string','database',1),f('sentTo','json','database',1),f('sentAt','datetime','database',1),f('resolvedAt','datetime','database')],ADM,0,0),
  e('aml-screening','ScreeningRecheckTask','Scheduled re-screening task',0,[f('taskId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('scheduledAt','datetime','database',1,0,1),f('recheckReason','string','database'),f('completedAt','datetime','database'),f('outcome','string','database'),f('triggeredBy','string','database',1)],SYS,0,0),
];
