'use strict';
let _c=8000;
const sid=()=>`s${String(++_c).padStart(5,'0')}`;
const f=(n,t,s,r,u,i,e)=>({id:sid(),name:n,type:t,storage:s,required:!!r,unique:!!u,indexed:!!i,encrypted:!!e});
const ADM={create:'admin',read:'admin',update:'admin',delete:'admin'};
const SYS={create:'admin',read:'auth',update:'admin',delete:'admin'};
const AUTH={create:'auth',read:'auth',update:'owner',delete:'admin'};
const PUB={create:'auth',read:'public',update:'owner',delete:'admin'};
const e=(m,n,d,c,fs,a,o,p)=>({id:sid(),moduleId:m,name:n,description:d||undefined,isCore:!!c,fields:fs,access:a||AUTH,onChain:!!o,apiPublic:p!==undefined?!!p:true});

module.exports=[
  /* ── traceability-ledger ── */
  e('traceability-ledger','MangoLot','Central lot record for a mango consignment',1,[f('lotId','uuid','database',1,1,1),f('lotNumber','string','on-chain',1,1,1),f('variety','string','on-chain',1,0,1),f('farmerId','uuid','on-chain',1,0,1),f('destinationCountry','string','on-chain',1,0,1),f('currentStage','string','on-chain',1,0,1),f('status','string','on-chain',1,0,1)],PUB,1,1),
  e('traceability-ledger','LotStageTransition','Immutable event-sourced stage history',1,[f('transitionId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('fromStage','string','on-chain',1),f('toStage','string','on-chain',1),f('triggeredBy','uuid','on-chain',1,0,1),f('txHash','bytes32','on-chain',1),f('transitionedAt','datetime','on-chain',1,0,1)],AUTH,1,1),
  e('traceability-ledger','LotConsignment','Groups multiple lots into one shipment',1,[f('consignmentId','uuid','database',1,1,1),f('consignmentNumber','string','on-chain',1,1,1),f('exporterId','uuid','on-chain',1,0,1),f('freightForwarderId','uuid','database'),f('status','string','on-chain',1,0,1),f('totalLots','int','database'),f('destinationCountry','string','on-chain',1)],AUTH,1,1),
  e('traceability-ledger','LotStatusSnapshot','Periodic snapshot of lot state',0,[f('snapshotId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('capturedAt','datetime','database',1,0,1),f('currentStage','string','database',1),f('currentQuantityKg','float','database'),f('activeAlerts','int','database'),f('snapshotHash','bytes32','database',1)],AUTH,0,0),
  e('traceability-ledger','LotAlertRecord','Alert raised against a lot',0,[f('alertId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('alertType','string','database',1,0,1),f('severity','string','database',1),f('message','text','database',1),f('createdAt','datetime','database',1),f('acknowledgedBy','uuid','database')],AUTH,0,1),
  e('traceability-ledger','ConsignmentMember','Lot assigned to a consignment',0,[f('memberId','uuid','database',1,1,1),f('consignmentId','uuid','database',1,0,1),f('lotId','uuid','database',1,0,1),f('addedAt','datetime','database',1),f('addedBy','uuid','database',1),f('weightKg','float','database'),f('boxCount','int','database')],AUTH,0,0),
  e('traceability-ledger','LotTrackingLink','Public tracking link for a lot',0,[f('linkId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('publicToken','string','database',1,1),f('createdAt','datetime','database',1),f('expiresAt','datetime','database'),f('viewCount','int','database'),f('lastViewedAt','datetime','database')],PUB,0,1),

  /* ── cold-chain-monitoring ── */
  e('cold-chain-monitoring','ColdChainProfile','Variety-specific cold chain parameters',1,[f('profileId','uuid','database',1,1,1),f('variety','string','database',1,1),f('optimalTempMin','float','database',1),f('optimalTempMax','float','database',1),f('maxHumidityPct','float','database'),f('alertCooldownMins','int','database',1),f('samplingIntervalSecs','int','database',1)],ADM,0,0),
  e('cold-chain-monitoring','ColdStorageEntry','Cold storage record for a lot',1,[f('entryId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,1,1),f('facilityId','uuid','on-chain',1,0,1),f('chamberNumber','string','database'),f('entryTimestamp','datetime','on-chain',1),f('exitTimestamp','datetime','on-chain'),f('targetTempCelsius','float','on-chain',1)],AUTH,1,1),
  e('cold-chain-monitoring','TemperatureReading','IoT temperature reading during cold storage',1,[f('readingId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('deviceId','uuid','database',1,0,1),f('tempCelsius','float','on-chain',1),f('recordedAt','datetime','on-chain',1,0,1),f('isBreach','boolean','on-chain',0,0,1),f('breachThreshold','float','on-chain')],AUTH,1,1),
  e('cold-chain-monitoring','HumidityReading','IoT humidity reading during cold storage',0,[f('readingId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('deviceId','uuid','database',1,0,1),f('humidityPct','float','database',1),f('recordedAt','datetime','database',1,0,1),f('isBreach','boolean','database',0,0,1),f('humidityThreshold','float','database')],AUTH,0,1),
  e('cold-chain-monitoring','IoTBreachAlert','On-chain alert for a sensor threshold breach',1,[f('alertId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('deviceId','uuid','on-chain',1),f('alertType','string','on-chain',1,0,1),f('measuredValue','float','on-chain',1),f('thresholdValue','float','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('cold-chain-monitoring','ShockSensorEvent','Impact/vibration event detected by IoT device',0,[f('eventId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('deviceId','uuid','database',1,0,1),f('accelerationG','float','database',1),f('stage','string','database',1,0,1),f('recordedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain')],AUTH,1,1),
  e('cold-chain-monitoring','ColdChainComplianceSummary','Summary compliance result for a lot in cold storage',0,[f('summaryId','uuid','database',1,1,1),f('lotId','uuid','database',1,1,1),f('storageEntryId','uuid','database',1),f('avgTempCelsius','float','database',1),f('maxTempCelsius','float','database',1),f('breachCount','int','database'),f('complianceStatus','string','database',1,0,1)],AUTH,0,1),

  /* ── port-customs-events ── */
  e('port-customs-events','ShippingBillRecord','ICEGATE shipping bill for export',1,[f('billId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('shippingBillNumber','string','on-chain',1,1,1),f('shippingBillDate','datetime','on-chain',1),f('portCode','string','on-chain',1,0,1),f('exporterIEC','string','on-chain',1),f('status','string','on-chain',1,0,1)],AUTH,1,1),
  e('port-customs-events','CustomsClearanceRecord','Export customs clearance event',1,[f('clearanceId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,1,1),f('brokerActorId','uuid','on-chain',1,0,1),f('shippingBillId','uuid','database',1,0,1),f('leoDate','datetime','on-chain',0,0,1),f('icegateRef','string','database'),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('port-customs-events','LETExportOrder','Let Export Order issued by customs',1,[f('leoId','uuid','database',1,1,1),f('clearanceId','uuid','on-chain',1,1,1),f('leoDate','datetime','on-chain',1),f('portCode','string','on-chain',1),f('authorizedBy','string','on-chain',1),f('leoDocHash','bytes32','on-chain',1),f('confirmedAt','datetime','on-chain',1)],AUTH,1,1),
  e('port-customs-events','PortArrivalNotice','Notice of lot arrival at destination port',0,[f('noticeId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('portCode','string','database',1,0,1),f('eta','datetime','database',1),f('notifiedAt','datetime','database',1),f('importingCountry','string','database',1),f('importEntryNumber','string','database')],AUTH,0,1),
  e('port-customs-events','PortReleaseOrder','Release order from destination port authorities',0,[f('releaseId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('portCode','string','on-chain',1),f('authorizedBy','string','on-chain',1),f('releaseDate','datetime','on-chain',1),f('releaseDocHash','bytes32','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('port-customs-events','CustomsInspectionResult','Result of customs inspection at export/import',0,[f('inspectionId','uuid','database',1,1,1),f('clearanceId','uuid','database',1,0,1),f('inspectedBy','string','database',1),f('inspectionDate','datetime','database',1),f('outcome','string','database',1,0,1),f('findingsSummary','text','database'),f('riskCategory','string','database',1)],AUTH,0,1),

  /* ── quality-recall-ledger ── */
  e('quality-recall-ledger','ResidueTestRecord','Lab residue test result for a lot',1,[f('testId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,1,1),f('labActorId','uuid','on-chain',1,0,1),f('testDate','datetime','on-chain',1),f('testMethod','string','on-chain',1),f('outcome','string','on-chain',1,0,1),f('reportPdfHash','bytes32','on-chain',1)],AUTH,1,1),
  e('quality-recall-ledger','PesticideCompoundDetail','Per-compound residue result',0,[f('detailId','uuid','database',1,1,1),f('testId','uuid','database',1,0,1),f('compound','string','database',1,0,1),f('detectedPPM','float','database',1),f('fssaiMRL','float','database',1),f('destMRL','float','database',1),f('exceedsDest','boolean','database',1)],AUTH,0,0),
  e('quality-recall-ledger','PackhouseProcessRecord','Packhouse grading and packing record',1,[f('processId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,1,1),f('packhouseActorId','uuid','on-chain',1,0,1),f('processDate','datetime','on-chain',1),f('acceptedQuantityKg','float','on-chain',1),f('rejectedQuantityKg','float','on-chain'),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('quality-recall-ledger','GradingBatchEntry','Grade breakdown within a packhouse session',0,[f('entryId','uuid','database',1,1,1),f('processId','uuid','database',1,0,1),f('gradeName','string','database',1,0,1),f('quantityKg','float','database',1),f('boxCount','int','database',1),f('avgWeightGrams','float','database'),f('labelingStandard','string','database')],AUTH,0,0),
  e('quality-recall-ledger','QualityAlertRecord','Quality alert raised for a lot',0,[f('alertId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('alertCategory','string','database',1,0,1),f('description','text','database',1),f('severity','string','database',1,0,1),f('raisedAt','datetime','database',1),f('resolvedAt','datetime','database')],AUTH,0,1),
  e('quality-recall-ledger','MRLExceedanceRecord','On-chain record of an MRL exceedance',0,[f('exceedanceId','uuid','database',1,1,1),f('testId','uuid','on-chain',1,0,1),f('compound','string','on-chain',1),f('detectedPPM','float','on-chain',1),f('allowedPPM','float','on-chain',1),f('exceedancePercent','float','on-chain'),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('quality-recall-ledger','ProductRecallOrder','Recall order for a failed lot',0,[f('recallId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('issuedBy','address','on-chain',1),f('recallReason','text','database',1),f('affectedQuantityKg','float','on-chain'),f('issuedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],ADM,1,0),

  /* ── evidence-chain ── */
  e('evidence-chain','EvidenceBundle','Assembled evidence package for a lot or dispute',1,[f('bundleId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('createdAt','datetime','on-chain',1),f('totalItems','int','database',1),f('bundleHash','bytes32','on-chain',1),f('signedBy','address','on-chain',1),f('disputeId','uuid','database')],AUTH,1,1),
  e('evidence-chain','EvidenceItem','Individual event within an evidence bundle',1,[f('itemId','uuid','database',1,1,1),f('bundleId','uuid','on-chain',1,0,1),f('eventType','string','on-chain',1),f('eventId','uuid','on-chain',1),f('eventTxHash','bytes32','on-chain',1),f('eventTimestamp','datetime','on-chain',1),f('sequenceNumber','int','on-chain',1)],AUTH,1,1),
  e('evidence-chain','EvidenceHashAnchor','On-chain hash anchor for an evidence item',0,[f('anchorId','uuid','database',1,1,1),f('itemId','uuid','on-chain',1,0,1),f('sha256Hash','bytes32','on-chain',1),f('anchoredAt','datetime','on-chain',1),f('anchoredBy','address','on-chain',1),f('txHash','bytes32','on-chain',1)],SYS,1,0),
  e('evidence-chain','ChainOfCustodyLink','Custody transfer link in the evidence chain',0,[f('linkId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('fromActorId','uuid','on-chain',1),f('toActorId','uuid','on-chain',1),f('custodyType','string','on-chain',1),f('transferTimestamp','datetime','on-chain',1),f('signatureHash','bytes32','on-chain',1)],AUTH,1,1),
  e('evidence-chain','EvidencePDFExport','Generated PDF export of an evidence bundle',0,[f('exportId','uuid','database',1,1,1),f('bundleId','uuid','database',1,0,1),f('generatedAt','datetime','database',1),f('pdfHash','bytes32','database',1),f('s3Key','string','database',1),f('generatedBy','uuid','database',1),f('downloadLink','string','database')],AUTH,0,0),
  e('evidence-chain','EvidenceIntegrityCheck','Integrity verification of an evidence bundle',0,[f('checkId','uuid','database',1,1,1),f('bundleId','uuid','database',1,0,1),f('checkedAt','datetime','database',1),f('allHashesValid','boolean','database',1),f('corruptedItems','int','database'),f('verifiedBy','uuid','database',1),f('outcome','string','database',1)],AUTH,0,0),

  /* ── trade-finance-docs ── */
  e('trade-finance-docs','CommercialInvoiceRecord','Commercial invoice for a lot shipment',1,[f('invoiceId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('invoiceNumber','string','database',1,1),f('exporterActorId','uuid','database',1,0,1),f('buyerActorId','uuid','database',1,0,1),f('totalValueUSD','float','database',1),f('invoicePdfHash','bytes32','database',1)],AUTH,0,1),
  e('trade-finance-docs','PackingListRecord','Packing list document for a shipment',0,[f('packingId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('invoiceId','uuid','database',1,0,1),f('totalBoxes','int','database',1),f('totalWeightKg','float','database',1),f('packingListHash','bytes32','database',1),f('generatedAt','datetime','database',1)],AUTH,0,0),
  e('trade-finance-docs','BillOfLadingRecord','Shipping line bill of lading',1,[f('blId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('blNumber','string','on-chain',1,1,1),f('shippingLineActorId','uuid','on-chain',1,0,1),f('vesselName','string','on-chain',1),f('containerNumber','string','on-chain',1,0,1),f('blDocHash','bytes32','on-chain',1)],AUTH,1,1),
  e('trade-finance-docs','BLAmendmentRecord','Amendment to a bill of lading',0,[f('amendmentId','uuid','database',1,1,1),f('blId','uuid','on-chain',1,0,1),f('amendmentNumber','int','database',1),f('changedFields','json','database',1),f('reason','text','database',1),f('amendedDocHash','bytes32','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('trade-finance-docs','InsuranceCertificateRecord','Insurance certificate for a lot shipment',0,[f('certId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('insurer','string','database',1),f('policyNumber','string','database',1,1),f('coverageAmountUSD','float','database',1),f('validFrom','datetime','database',1),f('certHash','bytes32','database',1)],AUTH,0,0),
  e('trade-finance-docs','LetterOfCreditRecord','Letter of credit from buyer bank',0,[f('lcId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('issuingBank','string','database',1),f('lcNumber','string','database',1,1),f('lcAmountUSD','float','database',1),f('expiryDate','datetime','database',1),f('lcHash','bytes32','database',1)],AUTH,0,0),

  /* ── compliance-attestations ── */
  e('compliance-attestations','PhytosanitaryCertificate','NPPO phytosanitary certificate for a lot',1,[f('certId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,1,1),f('inspectorActorId','uuid','on-chain',1,0,1),f('certNumber','string','on-chain',1,1,1),f('issuedAt','datetime','on-chain',1),f('validUntil','datetime','on-chain',1,0,1),f('certPdfHash','bytes32','on-chain',1)],PUB,1,1),
  e('compliance-attestations','PhytoInspectionFinding','Individual finding in a phyto inspection',0,[f('findingId','uuid','database',1,1,1),f('certId','uuid','database',1,0,1),f('inspectionPoint','string','database',1),f('finding','string','database',1),f('notes','text','database'),f('recordedAt','datetime','database',1),f('inspectedBy','uuid','database',1)],AUTH,0,0),
  e('compliance-attestations','APEDACertification','APEDA Certificate of Origin and EIC',1,[f('certId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,1,1),f('apedaOfficerActorId','uuid','on-chain',1,0,1),f('certOfOriginNumber','string','on-chain',1,1,1),f('exportInspCertNumber','string','on-chain',1,1),f('issueDate','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('compliance-attestations','ComplianceAttestation','Attestation issued by a regulatory authority',0,[f('attestationId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('authority','string','on-chain',1,0,1),f('attestationType','string','on-chain',1),f('outcome','string','on-chain',1,0,1),f('attestedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('compliance-attestations','TreatmentComplianceRecord','VHT/HWT treatment compliance record',1,[f('recordId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,1,1),f('treatmentType','string','on-chain',1),f('targetTemp','float','on-chain',1),f('actualTemp','float','on-chain',1),f('durationMins','int','on-chain',1),f('certHash','bytes32','on-chain',1)],AUTH,1,1),
  e('compliance-attestations','AttestationRenewalSchedule','Scheduled renewal for expiring attestations',0,[f('scheduleId','uuid','database',1,1,1),f('attestationId','uuid','database',1,1,1),f('nextRenewalAt','datetime','database',1,0,1),f('renewalReason','string','database'),f('reminderSentAt','datetime','database'),f('autoRenew','boolean','database'),f('renewedBy','uuid','database')],ADM,0,0),
  e('compliance-attestations','NonComplianceNotice','On-chain notice of a compliance violation',0,[f('noticeId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('authority','string','on-chain',1),f('noticeType','string','on-chain',1,0,1),f('description','text','database',1),f('issuedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],ADM,1,0),

  /* ── provenance-notary ── */
  e('provenance-notary','NotarizationRecord','On-chain notarization of a document',1,[f('notarizationId','uuid','database',1,1,1),f('documentId','uuid','database',1,0,1),f('sha256Hash','bytes32','on-chain',1),f('anchoredAt','datetime','on-chain',1),f('anchoredBy','address','on-chain',1),f('txHash','bytes32','on-chain',1),f('notarizationPurpose','string','database',1)],AUTH,1,1),
  e('provenance-notary','IPFSPinRecord','IPFS pin status for a document',0,[f('pinId','uuid','database',1,1,1),f('documentId','uuid','database',1,0,1),f('cid','string','database',1,1),f('pinService','string','database',1),f('pinnedAt','datetime','database',1),f('pinStatus','string','database',1,0,1),f('gatewayUrl','string','database')],AUTH,0,1),
  e('provenance-notary','DocumentHashRecord','On-chain anchored hash for any document',1,[f('hashId','uuid','database',1,1,1),f('documentId','uuid','on-chain',1,0,1),f('lotId','uuid','on-chain',0,0,1),f('sha256Hash','bytes32','on-chain',1),f('ipfsCid','string','database'),f('anchoredAt','datetime','on-chain',1),f('verifiable','boolean','on-chain',1)],PUB,1,1),
  e('provenance-notary','TimestampAnchor','On-chain timestamp anchor for any payload hash',0,[f('anchorId','uuid','database',1,1,1),f('payloadHash','bytes32','on-chain',1),f('anchoredAt','datetime','on-chain',1),f('blockHeight','int','on-chain',1,0,1),f('txHash','bytes32','on-chain',1),f('anchoredBy','address','on-chain',1)],SYS,1,0),
  e('provenance-notary','NotarizationBatch','Batch of documents notarized together',0,[f('batchId','uuid','database',1,1,1),f('documentCount','int','database',1),f('batchHash','bytes32','on-chain',1),f('submittedAt','datetime','database',1),f('confirmedAt','datetime','on-chain'),f('batchSize','int','database'),f('txHash','bytes32','on-chain',1)],AUTH,1,0),
  e('provenance-notary','ProvenanceVerification','Public verification check against a document hash',0,[f('verificationId','uuid','database',1,1,1),f('hashId','uuid','database',1,0,1),f('submittedHash','bytes32','database',1),f('verifiedAt','datetime','database',1),f('result','string','database',1,0,1),f('verifiedBy','uuid','database'),f('matchConfidence','float','database')],PUB,0,1),
];
