'use strict';
let _c=9000;
const sid=()=>`s${String(++_c).padStart(5,'0')}`;
const f=(n,t,s,r,u,i,e)=>({id:sid(),name:n,type:t,storage:s,required:!!r,unique:!!u,indexed:!!i,encrypted:!!e});
const ADM={create:'admin',read:'admin',update:'admin',delete:'admin'};
const SYS={create:'admin',read:'auth',update:'admin',delete:'admin'};
const AUTH={create:'auth',read:'auth',update:'owner',delete:'admin'};
const OWN={create:'owner',read:'owner',update:'owner',delete:'admin'};
const PUB={create:'auth',read:'public',update:'owner',delete:'admin'};
const e=(m,n,d,c,fs,a,o,p)=>({id:sid(),moduleId:m,name:n,description:d||undefined,isCore:!!c,fields:fs,access:a||AUTH,onChain:!!o,apiPublic:p!==undefined?!!p:true});

module.exports=[
  /* ── onchain-data ── */
  e('onchain-data','OnChainRecord','Immutable on-chain record for any entity',1,[f('recordId','uuid','database',1,1,1),f('entityType','string','on-chain',1,0,1),f('entityId','uuid','on-chain',1,0,1),f('dataHash','bytes32','on-chain',1),f('encryptedPayload','text','database',0,0,0,1),f('writtenAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],SYS,1,1),
  e('onchain-data','DataWriteTransaction','Metadata for every on-chain write operation',0,[f('txId','uuid','database',1,1,1),f('writerId','uuid','database',1,0,1),f('entityType','string','on-chain',1,0,1),f('entityId','uuid','on-chain',1,0,1),f('gasUsed','int','on-chain'),f('writtenAt','datetime','on-chain',1),f('blockHeight','int','on-chain',1,0,1)],SYS,1,0),
  e('onchain-data','StorageQuotaRecord','Storage quota usage per actor',0,[f('quotaId','uuid','database',1,1,1),f('actorId','uuid','database',1,1,1),f('usedBytes','int','database',1),f('quotaBytes','int','database',1),f('period','string','database',1),f('lastUpdatedAt','datetime','database',1),f('warningThreshold','float','database')],ADM,0,0),
  e('onchain-data','OnChainEventLog','Log of events emitted by on-chain contracts',1,[f('logId','uuid','database',1,1,1),f('eventType','string','on-chain',1,0,1),f('entityId','uuid','on-chain',1,0,1),f('eventPayload','json','database',1),f('emittedAt','datetime','on-chain',1),f('blockHeight','int','on-chain',1,0,1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('onchain-data','DataMigrationRecord','Record of a schema or data migration',0,[f('migrationId','uuid','database',1,1,1),f('fromVersion','string','database',1),f('toVersion','string','database',1),f('entitiesAffected','int','database'),f('migratedAt','datetime','database',1),f('migratedBy','address','database',1),f('status','string','database',1,0,1)],ADM,0,0),
  e('onchain-data','OnChainIndexEntry','Index entry for efficient on-chain lookups',0,[f('indexId','uuid','database',1,1,1),f('entityType','string','on-chain',1,0,1),f('entityId','uuid','on-chain',1,0,1),f('indexKey','string','on-chain',1,0,1),f('indexValue','string','on-chain',1),f('indexedAt','datetime','on-chain',1),f('blockHeight','int','on-chain',1)],SYS,1,0),

  /* ── oracles ── */
  e('oracles','OracleDataFeed','Configured oracle data source',1,[f('feedId','uuid','database',1,1,1),f('feedName','string','database',1,1),f('providerType','string','database',1,0,1),f('endpoint','string','database',1),f('dataSchema','json','database'),f('refreshIntervalSecs','int','database',1),f('isActive','boolean','database',1,0,1)],ADM,0,0),
  e('oracles','OracleDataPoint','Single data point ingested from an oracle feed',1,[f('pointId','uuid','database',1,1,1),f('feedId','uuid','on-chain',1,0,1),f('rawValue','json','database',1),f('normalizedValue','float','on-chain'),f('capturedAt','datetime','on-chain',1,0,1),f('quality','string','database'),f('blockHeight','int','on-chain',0,0,1)],AUTH,1,1),
  e('oracles','OracleFeedUpdate','Record of a feed value update',0,[f('updateId','uuid','database',1,1,1),f('feedId','uuid','on-chain',1,0,1),f('previousValue','json','database'),f('newValue','json','on-chain',1),f('updatedAt','datetime','on-chain',1),f('source','string','database',1),f('txHash','bytes32','on-chain')],SYS,1,0),
  e('oracles','OracleDispute','Dispute raised against an oracle value',0,[f('disputeId','uuid','database',1,1,1),f('feedId','uuid','database',1,0,1),f('disputedValue','json','database',1),f('expectedRange','json','database'),f('raisedBy','address','database',1),f('raisedAt','datetime','database',1),f('resolvedAt','datetime','database')],AUTH,0,0),
  e('oracles','OracleProviderConfig','Configuration for an oracle provider',0,[f('configId','uuid','database',1,1,1),f('providerName','string','database',1,1),f('endpoint','string','database',1),f('authType','string','database',1),f('signingKeyHash','bytes32','database',1),f('maxLatencyMs','int','database'),f('createdAt','datetime','database',1)],ADM,0,0),
  e('oracles','OracleHeartbeat','Periodic heartbeat to verify oracle liveness',0,[f('heartbeatId','uuid','database',1,1,1),f('feedId','uuid','database',1,0,1),f('pingAt','datetime','database',1),f('responseMs','int','database'),f('dataFreshness','string','database'),f('healthy','boolean','database',1,0,1),f('errorMessage','text','database')],SYS,0,0),

  /* ── webhooks-inbound ── */
  e('webhooks-inbound','InboundEndpoint','Registered inbound webhook endpoint',1,[f('endpointId','uuid','database',1,1,1),f('path','string','database',1,1),f('secretHash','bytes32','database',1),f('allowedSources','json','database'),f('maxBatchSize','int','database',1),f('createdAt','datetime','database',1),f('isActive','boolean','database',1,0,1)],ADM,0,0),
  e('webhooks-inbound','WebhookPayloadRecord','Inbound webhook payload received',0,[f('payloadId','uuid','database',1,1,1),f('endpointId','uuid','database',1,0,1),f('sourceIp','string','database',1,0,0,1),f('payloadHash','bytes32','database',1),f('receivedAt','datetime','database',1,0,1),f('processingStatus','string','database',1,0,1),f('errorMessage','text','database')],SYS,0,0),
  e('webhooks-inbound','HMACValidationLog','HMAC signature validation result',0,[f('validationId','uuid','database',1,1,1),f('payloadId','uuid','database',1,0,1),f('submittedSignatureHash','bytes32','database',1),f('computedSignatureHash','bytes32','database',1),f('isValid','boolean','database',1,0,1),f('validatedAt','datetime','database',1),f('rejectReason','string','database')],SYS,0,0),
  e('webhooks-inbound','InboundBatchRecord','Batch of inbound items processed together',0,[f('batchId','uuid','database',1,1,1),f('endpointId','uuid','database',1,0,1),f('itemCount','int','database',1),f('batchHash','bytes32','database',1),f('receivedAt','datetime','database',1),f('processedCount','int','database'),f('failedCount','int','database')],SYS,0,0),
  e('webhooks-inbound','InboundRetryRecord','Retry attempt for a failed payload',0,[f('retryId','uuid','database',1,1,1),f('payloadId','uuid','database',1,0,1),f('retryCount','int','database',1),f('lastRetryAt','datetime','database',1),f('nextRetryAt','datetime','database'),f('finalStatus','string','database',0,0,1),f('errorDetail','text','database')],SYS,0,0),
  e('webhooks-inbound','WebhookSecretConfig','Secret rotation config for a webhook endpoint',0,[f('configId','uuid','database',1,1,1),f('endpointId','uuid','database',1,1,1),f('secretHash','bytes32','database',1),f('rotatedAt','datetime','database'),f('rotatedBy','address','database'),f('expiresAt','datetime','database'),f('isActive','boolean','database',1)],ADM,0,0),

  /* ── webhooks-outbound ── */
  e('webhooks-outbound','OutboundTarget','Target system for outbound events',1,[f('targetId','uuid','database',1,1,1),f('targetName','string','database',1,1),f('url','string','database',1),f('authType','string','database',1),f('secretHash','bytes32','database',0,0,0,1),f('signingEnabled','boolean','database',1),f('isActive','boolean','database',1,0,1)],ADM,0,0),
  e('webhooks-outbound','OutboundDeliveryAttempt','Single delivery attempt to a target',0,[f('attemptId','uuid','database',1,1,1),f('targetId','uuid','database',1,0,1),f('eventType','string','database',1,0,1),f('eventId','uuid','database',1),f('payloadHash','bytes32','database',1),f('attemptedAt','datetime','database',1),f('statusCode','int','database',0,0,1)],SYS,0,0),
  e('webhooks-outbound','OutboundDeliveryReceipt','Confirmed receipt from a target system',0,[f('receiptId','uuid','database',1,1,1),f('attemptId','uuid','database',1,1,1),f('deliveredAt','datetime','database',1),f('responseBodyHash','bytes32','database'),f('latencyMs','int','database'),f('acknowledged','boolean','database',1),f('targetName','string','database',1)],SYS,0,0),
  e('webhooks-outbound','WebhookSignatureRecord','Signature applied to an outbound payload',0,[f('signatureId','uuid','database',1,1,1),f('attemptId','uuid','database',1,1,1),f('signature','bytes32','database',1),f('algorithm','string','database',1),f('signedPayloadHash','bytes32','database',1),f('signedAt','datetime','database',1)],SYS,0,0),
  e('webhooks-outbound','OutboundRetryPolicy','Retry policy for a target',0,[f('policyId','uuid','database',1,1,1),f('targetId','uuid','database',1,1,1),f('maxRetries','int','database',1),f('backoffSeconds','int','database',1),f('retryOnCodes','json','database'),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),
  e('webhooks-outbound','DeliveryFailureAlert','Alert for repeated delivery failures',0,[f('alertId','uuid','database',1,1,1),f('targetId','uuid','database',1,0,1),f('failedAttempts','int','database',1),f('firstFailedAt','datetime','database',1),f('lastFailedAt','datetime','database',1),f('alertSent','boolean','database',1),f('resolvedAt','datetime','database')],SYS,0,0),

  /* ── subgraph-indexer ── */
  e('subgraph-indexer','IndexedEntityRecord','An entity record indexed by the subgraph',1,[f('recordId','uuid','database',1,1,1),f('entityType','string','database',1,0,1),f('entityId','uuid','on-chain',1,0,1),f('indexedFields','json','database',1),f('indexedAt','datetime','database',1),f('blockHeight','int','on-chain',1,0,1),f('chainId','string','database',1)],SYS,1,1),
  e('subgraph-indexer','IndexerSyncStatus','Current sync status of the indexer',1,[f('statusId','uuid','database',1,1,1),f('chainId','string','database',1,1),f('latestIndexedBlock','int','database',1,0,1),f('latestChainBlock','int','database',1),f('lagBlocks','int','database'),f('syncedAt','datetime','database',1,0,1),f('healthy','boolean','database',1,0,1)],SYS,0,0),
  e('subgraph-indexer','SubgraphDeployment','Deployed subgraph version',0,[f('deploymentId','uuid','database',1,1,1),f('schemaVersion','string','database',1),f('startBlock','int','database',1),f('deployedAt','datetime','database',1),f('deployedBy','address','database',1),f('status','string','database',1,0,1),f('entityTypeCount','int','database')],ADM,0,0),
  e('subgraph-indexer','IndexerErrorRecord','Error encountered during indexing',0,[f('errorId','uuid','database',1,1,1),f('deploymentId','uuid','database',1,0,1),f('blockHeight','int','database',0,0,1),f('errorType','string','database',1,0,1),f('errorMessage','text','database',1),f('retried','boolean','database'),f('resolvedAt','datetime','database')],SYS,0,0),
  e('subgraph-indexer','SubgraphQueryLog','Log of queries served by the indexer',0,[f('logId','uuid','database',1,1,1),f('clientId','uuid','database',0,0,1),f('queryHash','bytes32','database',1),f('returnedRecords','int','database'),f('durationMs','int','database'),f('executedAt','datetime','database',1,0,1),f('cacheHit','boolean','database')],SYS,0,0),
  e('subgraph-indexer','IndexerHealthRecord','Periodic health snapshot of the indexer',0,[f('healthId','uuid','database',1,1,1),f('deploymentId','uuid','database',1,0,1),f('capturedAt','datetime','database',1,0,1),f('indexingRate','float','database'),f('errorRate','float','database'),f('uptimePct','float','database',1),f('warningCount','int','database')],SYS,0,0),

  /* ── notifications ── */
  e('notifications','NotificationTemplate','Template for a platform notification',1,[f('templateId','uuid','database',1,1,1),f('templateName','string','database',1,1),f('channel','string','database',1,0,1),f('subject','string','database',1),f('body','text','database',1),f('variables','json','database'),f('isActive','boolean','database',1)],ADM,0,0),
  e('notifications','NotificationRecord','A notification sent to an actor',0,[f('notifId','uuid','database',1,1,1),f('recipientActorId','uuid','database',1,0,1),f('templateId','uuid','database',1,0,1),f('channel','string','database',1,0,1),f('deliveryStatus','string','database',1,0,1),f('sentAt','datetime','database',1),f('readAt','datetime','database')],AUTH,0,0),
  e('notifications','NotificationPreference','Per-actor notification preference',0,[f('prefId','uuid','database',1,1,1),f('actorId','uuid','database',1,1,1),f('channel','string','database',1,0,1),f('eventType','string','database',1,0,1),f('enabled','boolean','database',1),f('updatedAt','datetime','database',1),f('quietHoursEnabled','boolean','database')],OWN,0,0),
  e('notifications','NotificationBatch','Batch notification send operation',0,[f('batchId','uuid','database',1,1,1),f('templateId','uuid','database',1,0,1),f('recipientCount','int','database',1),f('triggeredBy','uuid','database',1),f('sentAt','datetime','database',1),f('deliveredCount','int','database'),f('failedCount','int','database')],ADM,0,0),
  e('notifications','NotificationDeliveryError','Error in delivering a notification',0,[f('errorId','uuid','database',1,1,1),f('notifId','uuid','database',1,0,1),f('channel','string','database',1),f('errorCode','string','database',1),f('errorMessage','text','database',1),f('retryCount','int','database'),f('failedAt','datetime','database',1)],SYS,0,0),
  e('notifications','NotificationAcknowledgement','Actor acknowledgement of a notification',0,[f('ackId','uuid','database',1,1,1),f('notifId','uuid','database',1,0,1),f('actorId','uuid','database',1,0,1),f('acknowledgedAt','datetime','database',1),f('actionTaken','string','database'),f('deviceId','uuid','database'),f('ipAddress','string','database',0,0,0,1)],OWN,0,0),

  /* ── emails ── */
  e('emails','EmailTemplate','Email template for transactional sends',1,[f('templateId','uuid','database',1,1,1),f('templateName','string','database',1,1),f('fromEmail','string','database',1),f('subject','string','database',1),f('htmlBody','text','database',1),f('variables','json','database'),f('isActive','boolean','database',1)],ADM,0,0),
  e('emails','EmailSendRecord','Record of a sent transactional email',0,[f('sendId','uuid','database',1,1,1),f('templateId','uuid','database',1,0,1),f('recipientEmail','string','database',1,0,0,1),f('subject','string','database',1),f('sentAt','datetime','database',1),f('messageId','string','database',1,1),f('status','string','database',1,0,1)],SYS,0,0),
  e('emails','EmailBounceRecord','Bounce event for a sent email',0,[f('bounceId','uuid','database',1,1,1),f('sendId','uuid','database',1,0,1),f('bounceType','string','database',1,0,1),f('bouncedAt','datetime','database',1),f('bounceMessage','text','database'),f('suppressionAdded','boolean','database',1),f('recipientDomain','string','database')],SYS,0,0),
  e('emails','EmailUnsubscribeRecord','Unsubscribe event recorded for compliance',0,[f('unsubId','uuid','database',1,1,1),f('recipientEmail','string','database',1,0,0,1),f('actorId','uuid','database'),f('unsubscribedAt','datetime','database',1),f('reason','string','database'),f('listType','string','database',1),f('permanentBlock','boolean','database')],OWN,0,0),
  e('emails','EmailDeliveryStatus','Delivery status event from the email provider',0,[f('statusId','uuid','database',1,1,1),f('sendId','uuid','database',1,0,1),f('event','string','database',1,0,1),f('eventOccurredAt','datetime','database',1),f('provider','string','database',1),f('providerMessageId','string','database'),f('ipAddress','string','database',0,0,0,1)],SYS,0,0),
  e('emails','EmailRateLimitConfig','Rate limit config for outbound email',0,[f('configId','uuid','database',1,1,1),f('domain','string','database',1,1),f('maxPerMinute','int','database',1),f('maxPerHour','int','database',1),f('maxPerDay','int','database',1),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),

  /* ── audit-logs ── */
  e('audit-logs','AuditEntry','Tamper-evident audit log entry',1,[f('entryId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('action','string','database',1,0,1),f('resourceType','string','database',1,0,1),f('resourceId','uuid','database',1,0,1),f('changeHash','bytes32','on-chain',1),f('recordedAt','datetime','on-chain',1,0,1)],AUTH,1,1),
  e('audit-logs','AuditRetentionConfig','Retention policy per log category',1,[f('configId','uuid','database',1,1,1),f('logType','string','database',1,1),f('retentionYears','int','database',1),f('archiveAfterDays','int','database'),f('encryptArchives','boolean','database',1),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),
  e('audit-logs','AuditExportJob','Request to export a range of audit entries',0,[f('jobId','uuid','database',1,1,1),f('requestedBy','uuid','database',1,0,1),f('filters','json','database'),f('startDate','datetime','database',1),f('endDate','datetime','database',1),f('status','string','database',1,0,1),f('completedAt','datetime','database')],AUTH,0,0),
  e('audit-logs','AuditSearchIndex','Search index entry for audit records',0,[f('indexId','uuid','database',1,1,1),f('entryId','uuid','database',1,1,1),f('keywords','text','database',1),f('actorId','uuid','database',0,0,1),f('resourceType','string','database',0,0,1),f('indexedAt','datetime','database',1),f('relevanceScore','float','database')],SYS,0,0),
  e('audit-logs','AuditTamperDetection','Integrity check result for an audit entry',0,[f('detectionId','uuid','database',1,1,1),f('entryId','uuid','database',1,1,1),f('expectedHash','bytes32','database',1),f('computedHash','bytes32','database',1),f('integrityValid','boolean','database',1,0,1),f('checkedAt','datetime','database',1),f('checkedBy','string','database')],SYS,0,0),
  e('audit-logs','AuditAccessRecord','Record of who accessed audit log data',0,[f('accessId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('accessType','string','database',1),f('filteredBy','json','database'),f('exportedAt','datetime','database'),f('recordCount','int','database'),f('accessedAt','datetime','database',1,0,1)],AUTH,0,0),

  /* ── audit-export ── */
  e('audit-export','ExportJob','Job to generate a signed audit report',1,[f('jobId','uuid','database',1,1,1),f('lotId','uuid','database',0,0,1),f('requestedBy','uuid','database',1,0,1),f('requestedAt','datetime','database',1),f('status','string','database',1,0,1),f('completedAt','datetime','database'),f('deliveryMethod','string','database',1)],AUTH,0,0),
  e('audit-export','ExportedReport','Generated audit trail PDF report',0,[f('reportId','uuid','database',1,1,1),f('jobId','uuid','database',1,1,1),f('reportHash','bytes32','database',1),f('s3Key','string','database',1),f('generatedAt','datetime','database',1),f('pageCount','int','database'),f('reportType','string','database',1)],AUTH,0,0),
  e('audit-export','ReportChainSignature','On-chain signature anchoring a report',0,[f('signatureId','uuid','database',1,1,1),f('reportId','uuid','on-chain',1,0,1),f('signerKeyId','string','on-chain',1),f('signature','bytes32','on-chain',1),f('signedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],SYS,1,0),
  e('audit-export','ReportDeliveryRecord','Delivery of an export report to a recipient',0,[f('deliveryId','uuid','database',1,1,1),f('reportId','uuid','database',1,0,1),f('deliveredTo','uuid','database',1),f('deliveryMethod','string','database',1),f('deliveredAt','datetime','database',1),f('downloadCount','int','database'),f('lastDownloadAt','datetime','database')],AUTH,0,0),
  e('audit-export','ExportScheduleConfig','Schedule for automatic audit exports',0,[f('scheduleId','uuid','database',1,1,1),f('reportType','string','database',1),f('cronExpression','string','database',1),f('recipients','json','database',1),f('isEnabled','boolean','database',1),f('updatedBy','address','database',1),f('lastRunAt','datetime','database')],ADM,0,0),
  e('audit-export','ExportAccessPolicy','Access policy for exported reports',0,[f('policyId','uuid','database',1,1,1),f('reportType','string','database',1,1),f('allowedRoles','json','database',1),f('requiresApproval','boolean','database'),f('approverRole','string','database'),f('createdAt','datetime','database',1),f('updatedBy','address','database')],ADM,0,0),

  /* ── produce-grades ── */
  e('produce-grades','GradeInspectionRecord','Physical inspection to assign a produce grade',1,[f('inspectionId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('inspectorId','uuid','database',1,0,1),f('inspectionDate','datetime','database',1),f('variety','string','database',1,0,1),f('gradeName','string','database',1,0,1),f('inspectionFindings','text','database')],AUTH,0,1),
  e('produce-grades','GradeCertificateRecord','Certificate confirming produce grade',0,[f('certId','uuid','database',1,1,1),f('inspectionId','uuid','on-chain',1,0,1),f('gradeName','string','on-chain',1,0,1),f('quantityKg','float','on-chain',1),f('certHash','bytes32','on-chain',1),f('issuedAt','datetime','on-chain',1),f('issuedBy','uuid','on-chain',1)],AUTH,1,1),
  e('produce-grades','GradeAppealRecord','Appeal against a grading decision',0,[f('appealId','uuid','database',1,1,1),f('inspectionId','uuid','database',1,0,1),f('appealedBy','uuid','database',1,0,1),f('appealReason','text','database',1),f('appealedAt','datetime','database',1),f('outcome','string','database',0,0,1),f('resolvedAt','datetime','database')],AUTH,0,0),
  e('produce-grades','PackagingComplianceCheck','Check that packaging meets market requirements',0,[f('checkId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('labelingStandard','string','database',1,0,1),f('labelingCompliant','boolean','database',1),f('packagingMaterial','string','database'),f('checkedAt','datetime','database',1),f('checkedBy','uuid','database',1)],AUTH,0,0),
  e('produce-grades','LabelingComplianceRecord','Labeling compliance per destination market',0,[f('recordId','uuid','database',1,1,1),f('lotId','uuid','database',1,0,1),f('market','string','database',1,0,1),f('requiredLabels','json','database',1),f('presentLabels','json','database',1),f('compliant','boolean','database',1,0,1),f('checkedAt','datetime','database',1)],AUTH,0,0),
  e('produce-grades','GradeStandardVersion','Versioned grade standard definition',0,[f('versionId','uuid','database',1,1,1),f('standardName','string','database',1),f('market','string','database',1,0,1),f('effectiveFrom','datetime','database',1,0,1),f('gradeDefinitions','json','database',1),f('publishedBy','address','database',1),f('isActive','boolean','database',1)],ADM,0,0),

  /* ── document-signing ── */
  e('document-signing','SigningRequest','Request to sign a document',1,[f('requestId','uuid','database',1,1,1),f('documentId','uuid','database',1,0,1),f('lotId','uuid','database',0,0,1),f('requestedBy','uuid','database',1,0,1),f('signerActorIds','json','database',1),f('deadline','datetime','database'),f('status','string','database',1,0,1)],AUTH,0,0),
  e('document-signing','SignatureRecord','Captured signature on a document',1,[f('signatureId','uuid','database',1,1,1),f('requestId','uuid','on-chain',1,0,1),f('signerActorId','uuid','on-chain',1,0,1),f('signatureHash','bytes32','on-chain',1),f('signedAt','datetime','on-chain',1),f('method','string','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('document-signing','SignatureVerificationLog','Verification check on a stored signature',0,[f('verificationId','uuid','database',1,1,1),f('signatureId','uuid','database',1,0,1),f('verifiedBy','uuid','database',1),f('verifiedAt','datetime','database',1),f('result','string','database',1,0,1),f('submittedHash','bytes32','database',1),f('matchScore','float','database')],AUTH,0,0),
  e('document-signing','CoSignerRecord','Additional co-signer for a document',0,[f('coSignerId','uuid','database',1,1,1),f('requestId','uuid','on-chain',1,0,1),f('coSignerActorId','uuid','on-chain',1,0,1),f('coSignedAt','datetime','on-chain',1),f('signatureHash','bytes32','on-chain',1),f('method','string','on-chain',1),f('txHash','bytes32','on-chain')],AUTH,1,0),
  e('document-signing','SigningCertificateRecord','Certificate used for document signing',0,[f('certId','uuid','database',1,1,1),f('signerActorId','uuid','database',1,0,1),f('certHash','bytes32','database',1),f('issuedAt','datetime','database',1),f('expiresAt','datetime','database',1,0,1),f('provider','string','database',1),f('isActive','boolean','database',1)],AUTH,0,0),
  e('document-signing','DocuSignCallbackLog','Callback event received from DocuSign',0,[f('callbackId','uuid','database',1,1,1),f('requestId','uuid','database',0,0,1),f('envelopeId','string','database',1,0,1),f('event','string','database',1,0,1),f('eventAt','datetime','database',1),f('rawPayloadHash','bytes32','database',1),f('processed','boolean','database',1)],SYS,0,0),

  /* ── fraud-rules ── */
  e('fraud-rules','FraudRuleDefinition','Definition of a fraud detection rule',1,[f('ruleId','uuid','database',1,1,1),f('ruleName','string','database',1,1),f('ruleType','string','database',1,0,1),f('conditions','json','database',1),f('severity','string','database',1,0,1),f('isActive','boolean','database',1),f('createdBy','address','database',1)],ADM,0,0),
  e('fraud-rules','FraudDetectionEvent','Fraud pattern detected by the rules engine',0,[f('eventId','uuid','database',1,1,1),f('ruleId','uuid','on-chain',1,0,1),f('lotId','uuid','on-chain',0,0,1),f('actorId','uuid','on-chain',0,0,1),f('detectedAt','datetime','on-chain',1),f('evidenceHash','bytes32','on-chain',1),f('status','string','on-chain',1,0,1)],SYS,1,0),
  e('fraud-rules','FraudCaseRecord','Case opened for a detected fraud event',0,[f('caseId','uuid','database',1,1,1),f('eventId','uuid','database',1,1,1),f('assignedTo','uuid','database',0,0,1),f('severity','string','database',1,0,1),f('status','string','database',1,0,1),f('openedAt','datetime','database',1),f('resolvedAt','datetime','database')],ADM,0,0),
  e('fraud-rules','FraudAlertNotification','Alert sent for a fraud case',0,[f('alertId','uuid','database',1,1,1),f('caseId','uuid','database',1,0,1),f('notifiedActors','json','database',1),f('channel','string','database',1),f('sentAt','datetime','database',1),f('acknowledged','boolean','database'),f('ackAt','datetime','database')],ADM,0,0),
  e('fraud-rules','FraudReviewDecision','Decision on a fraud case',0,[f('decisionId','uuid','database',1,1,1),f('caseId','uuid','on-chain',1,0,1),f('reviewedBy','uuid','on-chain',1),f('decision','string','on-chain',1,0,1),f('reasoning','text','database',1),f('decidedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],ADM,1,0),
  e('fraud-rules','FraudPatternLog','Log of recurring fraud patterns',0,[f('patternId','uuid','database',1,1,1),f('patternType','string','database',1,0,1),f('occurrences','int','database',1),f('firstSeenAt','datetime','database',1),f('lastSeenAt','datetime','database',1,0,1),f('riskScore','float','database',1),f('flagged','boolean','database',1)],ADM,0,0),

  /* ── privacy-compliance ── */
  e('privacy-compliance','DataSubjectRequest','Data subject rights request (PDPB)',0,[f('requestId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('requestType','string','database',1,0,1),f('submittedAt','datetime','database',1),f('status','string','database',1,0,1),f('completedAt','datetime','database'),f('handledBy','uuid','database')],OWN,0,0),
  e('privacy-compliance','DataRetentionRecord','Data retention policy per field type',1,[f('retentionId','uuid','database',1,1,1),f('entityType','string','database',1,0,1),f('fieldName','string','database',1,0,1),f('retentionDays','int','database',1),f('archiveStrategy','string','database',1),f('reviewedAt','datetime','database'),f('updatedBy','address','database',1)],ADM,0,0),
  e('privacy-compliance','ConsentRecord','Actor consent record for data usage',0,[f('consentId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('consentType','string','database',1,0,1),f('granted','boolean','database',1),f('grantedAt','datetime','database',1),f('revokedAt','datetime','database'),f('version','string','database',1)],OWN,0,0),
  e('privacy-compliance','DataDeletionRecord','Record of data deleted on request',0,[f('deletionId','uuid','database',1,1,1),f('requestId','uuid','database',1,0,1),f('entityType','string','database',1),f('entityId','uuid','database',1),f('deletedAt','datetime','database',1),f('deletedBy','address','database',1),f('verificationHash','bytes32','database')],ADM,0,0),
  e('privacy-compliance','PrivacyImpactAssessment','DPIA for a new feature or data use',0,[f('assessmentId','uuid','database',1,1,1),f('featureName','string','database',1),f('riskLevel','string','database',1,0,1),f('mitigations','json','database',1),f('assessedBy','address','database',1),f('assessedAt','datetime','database',1),f('approved','boolean','database',1)],ADM,0,0),
  e('privacy-compliance','DataBreachNotice','Regulatory notice for a data breach',0,[f('noticeId','uuid','database',1,1,1),f('breachType','string','on-chain',1,0,1),f('affectedActorCount','int','database',1),f('detectedAt','datetime','on-chain',1),f('notifiedAt','datetime','database'),f('remediation','text','database',1),f('txHash','bytes32','on-chain')],ADM,1,0),

  /* ── treasury ── */
  e('treasury','TreasuryAccount','AGT treasury account',1,[f('accountId','uuid','database',1,1,1),f('accountName','string','on-chain',1,1),f('walletAddress','address','on-chain',1,1,1),f('accountType','string','on-chain',1,0,1),f('currentBalanceAGT','float','on-chain',1),f('lastUpdatedAt','datetime','database'),f('isActive','boolean','on-chain',1)],ADM,1,0),
  e('treasury','TreasuryTransaction','Movement of AGT between treasury accounts',1,[f('txId','uuid','database',1,1,1),f('fromAccount','address','on-chain',1,0,1),f('toAccount','address','on-chain',1,0,1),f('amountAGT','float','on-chain',1),f('purpose','string','on-chain',1),f('txHash','bytes32','on-chain',1),f('executedAt','datetime','on-chain',1)],ADM,1,0),
  e('treasury','FundAllocationRecord','Allocation of treasury funds to a purpose',0,[f('allocationId','uuid','database',1,1,1),f('accountId','uuid','on-chain',1,0,1),f('allocatedTo','string','on-chain',1),f('amountAGT','float','on-chain',1),f('allocationPurpose','string','on-chain',1),f('allocationDate','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],ADM,1,0),
  e('treasury','TreasuryReserveSnapshot','Snapshot of total treasury reserves',0,[f('snapshotId','uuid','database',1,1,1),f('capturedAt','datetime','database',1,0,1),f('totalAGT','float','on-chain',1),f('breakdown','json','database',1),f('percentReserve','float','database'),f('authorizedBy','address','database',1),f('blockHeight','int','on-chain',1)],ADM,1,0),
  e('treasury','TreasurySpendProposal','Proposal to spend treasury funds',0,[f('proposalId','uuid','database',1,1,1),f('proposedBy','address','on-chain',1,0,1),f('amountAGT','float','on-chain',1),f('recipient','address','on-chain',1),f('purpose','text','on-chain',1),f('proposedAt','datetime','on-chain',1),f('status','string','on-chain',1,0,1)],ADM,1,0),
  e('treasury','TreasuryGovernanceVote','Vote on a treasury spend proposal',0,[f('voteId','uuid','database',1,1,1),f('proposalId','uuid','on-chain',1,0,1),f('voterAddress','address','on-chain',1,0,1),f('vote','string','on-chain',1),f('tokensWeighted','float','on-chain',1),f('votedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),

  /* ── escrow-settlement ── */
  e('escrow-settlement','EscrowLock','Funds locked in escrow for a lot',1,[f('lockId','uuid','database',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('buyerActorId','uuid','on-chain',1,0,1),f('exporterActorId','uuid','on-chain',1,0,1),f('amountUSD','float','on-chain',1),f('lockedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('escrow-settlement','EscrowRelease','Escrow funds released to a party',0,[f('releaseId','uuid','database',1,1,1),f('lockId','uuid','on-chain',1,0,1),f('releasedTo','address','on-chain',1),f('amountReleased','float','on-chain',1),f('releasedAt','datetime','on-chain',1),f('triggerEvent','string','on-chain',1),f('txHash','bytes32','on-chain',1)],SYS,1,0),
  e('escrow-settlement','EscrowDisputeHold','Funds held pending dispute resolution',0,[f('holdId','uuid','database',1,1,1),f('lockId','uuid','on-chain',1,0,1),f('disputeId','uuid','on-chain',1,0,1),f('heldAt','datetime','on-chain',1),f('holdReason','string','on-chain',1),f('resolvedAt','datetime','on-chain'),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('escrow-settlement','EscrowRefundRecord','Escrow funds refunded to buyer',0,[f('refundId','uuid','database',1,1,1),f('lockId','uuid','on-chain',1,0,1),f('refundedTo','address','on-chain',1),f('refundAmount','float','on-chain',1),f('refundReason','string','on-chain',1),f('refundedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],SYS,1,0),
  e('escrow-settlement','EscrowPolicyConfig','Policy governing escrow terms',0,[f('configId','uuid','database',1,1,1),f('holdPeriodHours','int','database',1),f('releaseCondition','string','database',1),f('maxEscrowUSD','float','database'),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1),f('notes','text','database')],ADM,0,0),
  e('escrow-settlement','EscrowAuditEntry','Audit entry for escrow operations',0,[f('auditId','uuid','database',1,1,1),f('lockId','uuid','on-chain',1,0,1),f('action','string','on-chain',1),f('actorId','uuid','on-chain',1),f('amountInvolved','float','on-chain'),f('txHash','bytes32','on-chain',1),f('auditedAt','datetime','on-chain',1)],ADM,1,0),

  /* ── invoices-billing ── */
  e('invoices-billing','InvoiceRecord','Platform invoice for a billing period',1,[f('invoiceId','uuid','database',1,1,1),f('invoiceNumber','string','database',1,1),f('orgId','uuid','database',1,0,1),f('billingPeriod','string','database',1),f('subtotalINR','float','database',1),f('taxINR','float','database',1),f('status','string','database',1,0,1)],AUTH,0,1),
  e('invoices-billing','InvoiceLineItem','Line item within an invoice',0,[f('lineId','uuid','database',1,1,1),f('invoiceId','uuid','database',1,0,1),f('description','string','database',1),f('quantity','int','database',1),f('unitPriceINR','float','database',1),f('totalINR','float','database',1),f('lotReference','string','database')],AUTH,0,0),
  e('invoices-billing','PaymentRecord','Payment against an invoice',0,[f('paymentId','uuid','database',1,1,1),f('invoiceId','uuid','database',1,0,1),f('amountINR','float','database',1),f('paymentMethod','string','database',1,0,1),f('transactionRef','string','database',1,1),f('paidAt','datetime','database',1),f('status','string','database',1,0,1)],AUTH,0,0),
  e('invoices-billing','TaxCalculationRecord','GST calculation record per invoice',0,[f('taxId','uuid','database',1,1,1),f('invoiceId','uuid','database',1,1,1),f('baseAmount','float','database',1),f('taxType','string','database',1),f('taxPercent','float','database',1),f('taxAmount','float','database',1),f('computedAt','datetime','database',1)],AUTH,0,0),
  e('invoices-billing','BillingCycleRecord','Monthly billing cycle summary per org',0,[f('cycleId','uuid','database',1,1,1),f('orgId','uuid','database',1,0,1),f('cycleStart','datetime','database',1),f('cycleEnd','datetime','database',1),f('totalLots','int','database'),f('totalBilledINR','float','database',1),f('cycleStatus','string','database',1,0,1)],ADM,0,0),
  e('invoices-billing','CreditNoteRecord','Credit note issued against an invoice',0,[f('creditId','uuid','database',1,1,1),f('invoiceId','uuid','database',1,0,1),f('creditReason','text','database',1),f('creditAmountINR','float','database',1),f('issuedAt','datetime','database',1),f('issuedBy','address','database',1),f('appliedAt','datetime','database')],ADM,0,0),

  /* ── razorpay-adapter ── */
  e('razorpay-adapter','RazorpayOrder','Razorpay payment order',1,[f('orderId','uuid','database',1,1,1),f('razorpayOrderId','string','database',1,1),f('invoiceId','uuid','database',1,0,1),f('amountPaise','int','database',1),f('currency','string','database',1),f('status','string','database',1,0,1),f('createdAt','datetime','database',1)],AUTH,0,0),
  e('razorpay-adapter','RazorpayPaymentRecord','Captured Razorpay payment',0,[f('paymentId','uuid','database',1,1,1),f('orderId','uuid','database',1,0,1),f('razorpayPaymentId','string','database',1,1),f('method','string','database',1,0,1),f('amountPaise','int','database',1),f('capturedAt','datetime','database',1),f('status','string','database',1,0,1)],AUTH,0,0),
  e('razorpay-adapter','RazorpayRefundRecord','Razorpay refund against a payment',0,[f('refundId','uuid','database',1,1,1),f('paymentId','uuid','database',1,0,1),f('razorpayRefundId','string','database',1,1),f('amountPaise','int','database',1),f('refundReason','string','database',1),f('initiatedAt','datetime','database',1),f('status','string','database',1,0,1)],AUTH,0,0),
  e('razorpay-adapter','RazorpayWebhookLog','Incoming webhook event from Razorpay',0,[f('webhookId','uuid','database',1,1,1),f('eventType','string','database',1,0,1),f('payloadHash','bytes32','database',1),f('receivedAt','datetime','database',1),f('processed','boolean','database',1,0,1),f('processingError','text','database'),f('razorpayEventId','string','database',0,1)],SYS,0,0),
  e('razorpay-adapter','UPITransactionRecord','UPI transaction linked to a payment',0,[f('upiTxId','uuid','database',1,1,1),f('paymentId','uuid','database',1,0,1),f('vpa','string','database',1,0,0,1),f('status','string','database',1,0,1),f('upiRef','string','database',1,1),f('amountINR','float','database',1),f('completedAt','datetime','database')],AUTH,0,0),
  e('razorpay-adapter','RazorpayReconciliationRecord','Periodic reconciliation of Razorpay settlements',0,[f('reconId','uuid','database',1,1,1),f('period','string','database',1,0,1),f('ordersCount','int','database',1),f('paymentsTotal','float','database',1),f('refundsTotal','float','database'),f('discrepancy','float','database'),f('reconciledAt','datetime','database',1)],ADM,0,0),

  /* ── soulbound-token ── */
  e('soulbound-token','SoulboundTokenRecord','Non-transferable certificate token',1,[f('tokenId','uint256','on-chain',1,1,1),f('lotId','uuid','on-chain',1,0,1),f('certType','string','on-chain',1,0,1),f('issuedToActorId','uuid','on-chain',1,0,1),f('issuedByActorId','uuid','on-chain',1),f('mintedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],AUTH,1,1),
  e('soulbound-token','SBTRevocationRecord','On-chain revocation of a soulbound token',0,[f('revocationId','uuid','database',1,1,1),f('tokenId','uint256','on-chain',1,0,1),f('revokedBy','address','on-chain',1),f('revocationReason','string','database',1),f('revokedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],ADM,1,0),
  e('soulbound-token','SBTIssuanceCriteria','Criteria for minting a specific SBT type',0,[f('criteriaId','uuid','database',1,1,1),f('certType','string','database',1,1),f('issuerRole','string','database',1),f('requiredPreconditions','json','database',1),f('isActive','boolean','database',1),f('updatedBy','address','database',1),f('effectiveFrom','datetime','database',1)],ADM,0,0),
  e('soulbound-token','SBTMetadataRecord','Metadata JSON for a soulbound token',0,[f('metadataId','uuid','database',1,1,1),f('tokenId','uint256','on-chain',1,1,1),f('metadataJson','json','database',1),f('ipfsCid','string','database',0,1),f('updatedAt','datetime','database',1),f('contentHash','bytes32','database',1),f('pinStatus','string','database')],AUTH,0,1),
  e('soulbound-token','SBTVerificationRequest','Request to publicly verify an SBT',0,[f('requestId','uuid','database',1,1,1),f('tokenId','uint256','database',1,0,1),f('requestedBy','uuid','database'),f('requestedAt','datetime','database',1),f('verificationResult','string','database',1,0,1),f('verifiedAt','datetime','database'),f('chainConfirmed','boolean','database',1)],PUB,0,1),
  e('soulbound-token','SBTHolderRecord','Current SBT holdings per actor',0,[f('holderId','uuid','database',1,1,1),f('actorId','uuid','database',1,0,1),f('tokenId','uint256','on-chain',1,0,1),f('certType','string','on-chain',1,0,1),f('heldSince','datetime','on-chain',1),f('isRevoked','boolean','on-chain',1),f('lastVerifiedAt','datetime','database')],AUTH,1,1),

  /* ── erc721 ── */
  e('erc721','NFTCollection','ERC-721 collection contract configuration',1,[f('collectionId','uuid','database',1,1,1),f('name','string','on-chain',1),f('symbol','string','on-chain',1,1),f('contractAddress','address','on-chain',1,1,1),f('totalSupply','int','on-chain'),f('baseUri','string','database',1),f('deployedAt','datetime','on-chain',1)],ADM,1,1),
  e('erc721','NFTTokenRecord','Individual ERC-721 token',1,[f('tokenId','uint256','on-chain',1,1,1),f('collectionId','uuid','database',1,0,1),f('ownerAddress','address','on-chain',1,0,1),f('lotId','uuid','on-chain',0,0,1),f('certType','string','on-chain',0,0,1),f('mintedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],PUB,1,1),
  e('erc721','NFTTransferRecord','Token transfer event',0,[f('transferId','uuid','database',1,1,1),f('tokenId','uint256','on-chain',1,0,1),f('fromAddress','address','on-chain',1),f('toAddress','address','on-chain',1),f('transferredAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],PUB,1,1),
  e('erc721','NFTMetadataRecord','On-chain metadata for a token',0,[f('metadataId','uuid','database',1,1,1),f('tokenId','uint256','on-chain',1,1,1),f('metadataJson','json','database',1),f('ipfsCid','string','database',0,1),f('attributes','json','database'),f('updatedAt','datetime','database',1),f('contentHash','bytes32','database',1)],PUB,0,1),
  e('erc721','NFTMintRequest','Request to mint an ERC-721 token',0,[f('requestId','uuid','database',1,1,1),f('collectionId','uuid','database',1,0,1),f('recipientAddress','address','database',1),f('certType','string','database',1,0,1),f('lotId','uuid','database',0,0,1),f('requestedAt','datetime','database',1),f('status','string','database',1,0,1)],AUTH,0,0),
  e('erc721','NFTBurnRecord','Token burn record',0,[f('burnId','uuid','database',1,1,1),f('tokenId','uint256','on-chain',1,0,1),f('burnedBy','address','on-chain',1),f('burnReason','string','database',1),f('burnedAt','datetime','on-chain',1),f('txHash','bytes32','on-chain',1)],ADM,1,0),
];
